# -*- coding: utf-8 -*-
# North Dublin areas. `char` = housing stock, `cond` = what that means for gutters.
NORTH = [
 dict(slug="swords", name="Swords", label="Co. Dublin", sub="North County Dublin", exists=True,
  char="Swords has grown from a village into one of the biggest towns in the county, and the housing tells that story — the older streets around Main Street and Seatown, the big 1970s and 80s estates at River Valley and Boroimhe, and the newer apartment blocks out towards Airside.",
  cond="Being flat and open, with the airport just down the road, Swords catches a lot of wind. Loose brackets and joints that have worked themselves apart are the two things we're called out for most.",
  nb=["Malahide","Donabate","Portmarnock","Kinsealy","Rivervalley","Boroimhe","Brackenstown","Airside","Balheary","St Doulagh's","Lissenhall","Forrest Little"],
  revs=[("Gutters had come away from the fascia at the back and were pouring down the wall. Fixed and resecured the same week.","Declan M.","River Valley"),
        ("Full replacement on a 1980s semi. Matched the colour, tidied up after themselves, no complaints at all.","Aoife K.","Boroimhe"),
        ("Called about a blockage, they found the downpipe was cracked underground. Explained it properly instead of just guessing.","Tom B.","Brackenstown")]),
 dict(slug="malahide", name="Malahide", label="Co. Dublin", sub="North County Dublin",
  char="Malahide mixes handsome period houses near the village and the Marina with big detached family homes out along the coast road and the estates around Biscayne and Seabury.",
  cond="It's a coastal village, and salt air is hard on metal — brackets rust, fixings loosen and cast iron pits far faster here than it does inland. We use marine-grade fixings on coastal jobs for that reason.",
  nb=["Portmarnock","Swords","Kinsealy","Seabury","Biscayne","Robswall","Yellow Walls","Texas Lane","Gaybrook","Malahide Marina"],
  revs=[("Salt had eaten the old brackets on a house facing the estuary. New gutters and stainless fixings — no drama since.","Fiona D.","Seabury"),
        ("Seagulls had a nest wedged in the valley gutter. Cleared it out and fitted guards so it wouldn't happen again.","Michael O.","Yellow Walls"),
        ("Period house near the village, they were careful with the original cast iron and only replaced what had actually failed.","Sarah H.","Malahide Village")]),
 dict(slug="portmarnock", name="Portmarnock", label="Co. Dublin", sub="North County Dublin",
  char="Portmarnock runs from the older houses near the station out to the big estates behind the Velvet Strand, with a lot of 1970s and 80s bungalows and dormers in between.",
  cond="Nowhere in Dublin is more exposed to onshore wind than the streets behind the beach. Sand and salt get into everything, and gutters facing the sea need checking far more often than the ones on the sheltered side.",
  nb=["Malahide","Baldoyle","Sutton","Kinsealy","Velvet Strand","Strand Road","Carrickhill","Blackwood","Moyclare"],
  revs=[("Wind took a section clean off the front. Out the next morning, back up and properly braced this time.","Ronan G.","Strand Road"),
        ("Twenty-year-old PVC had gone brittle from the sun and salt. Replaced the lot, looks like a different house.","Claire N.","Carrickhill"),
        ("Straight answer on the phone, straight price on the day. That's all I wanted.","Peter L.","Moyclare")]),
 dict(slug="howth", name="Howth", label="Dublin 13", sub="North Dublin",
  char="Howth is built into a hill, so you get everything from cottages down at the harbour to large houses stepped up the Summit with steep roofs and long gutter runs.",
  cond="Two things make Howth hard on gutters: the exposure at the top of the hill, and the sheer volume of water a steep roof throws into a gutter during heavy rain. Undersized or badly-fallen gutters overflow here long before they would elsewhere.",
  nb=["Sutton","Baldoyle","Portmarnock","Howth Summit","Howth Harbour","Balscadden","Claremont","Thormanby Road","Kilrock"],
  revs=[("House up near the Summit, gutters couldn't cope in heavy rain. They upsized the run and added a second downpipe. Solved."," Gerard F.","Howth Summit"),
        ("Cast iron on an old harbour cottage — repaired rather than ripped out, which is what I was hoping for.","Niamh C.","Howth Harbour"),
        ("Very tidy job on a steep roof I wouldn't go near myself. Fully insured, which mattered to me.","David W.","Thormanby Road")]),
 dict(slug="sutton", name="Sutton", label="Dublin 13", sub="North Dublin",
  char="Sutton is mostly comfortable detached and semi-detached housing on the flat stretch between the sea on both sides, with a good number of 1960s and 70s bungalows.",
  cond="Water on two sides means salt on two sides. Bungalow gutters sit low and fill quickly with leaves off the mature gardens around Burrow Road, so cleaning tends to be a twice-a-year job rather than annual.",
  nb=["Howth","Baldoyle","Kilbarrack","Raheny","Burrow Road","Strand Road","Sutton Cross","Offington","St Fintan's"],
  revs=[("Two cleans a year now and no more overflow at the back. Reliable and on time both visits.","Margaret D.","Burrow Road"),
        ("Bungalow gutters were sagging in the middle. Rebracketed the whole run for a fair price.","Alan T.","Offington"),
        ("Storm damage on the seaward side. Temporary fix same day, proper repair that week.","Louise M.","Sutton Cross")]),
 dict(slug="baldoyle", name="Baldoyle", label="Dublin 13", sub="North Dublin",
  char="Baldoyle has the old village core, a big stretch of corporation and council-built housing from the 1950s and 60s, and the newer developments out at the Coast Road and Red Arches.",
  cond="A lot of the older housing still has its original narrow gutters, which simply weren't sized for the rainfall we get now. On the newer estates it's usually joints and brackets rather than the gutter itself.",
  nb=["Portmarnock","Sutton","Donaghmede","Bayside","Red Arches","Coast Road","Grange","Moyne Park","Baldoyle Village"],
  revs=[("Original gutters on a 1950s house, far too small. Upsized them and the overflow stopped straight away.","Kevin S.","Baldoyle Village"),
        ("New estate, badly fitted gutters from the builder. They put it right properly.","Emma J.","Red Arches"),
        ("Good honest crowd. Didn't try to sell me a full replacement when a repair would do.","Joseph R.","Grange")]),
 dict(slug="donaghmede", name="Donaghmede", label="Dublin 13", sub="North Dublin",
  char="Donaghmede is largely 1970s estate housing — long terraces and semis around the shopping centre, Grange Abbey and Elm Mount, most of it built to a similar pattern.",
  cond="When a whole estate goes up at once, the gutters reach the end of their life at once too. We're doing a lot of full replacements around Donaghmede now on systems that are simply past fifty years of service.",
  nb=["Baldoyle","Kilbarrack","Coolock","Bayside","Ayrfield","Grange Abbey","Clongriffin","Belmayne","Edenmore"],
  revs=[("Whole estate is at the same stage. Ours was the third house on the road they did — neighbours recommended them.","Bernadette K.","Grange Abbey"),
        ("Replaced gutters, fascia and soffit in two days. House looks ten years younger.","Stephen A.","Ayrfield"),
        ("Quoted, arrived, did exactly what they said. Rare enough.","Paula M.","Donaghmede")]),
 dict(slug="clontarf", name="Clontarf", label="Dublin 3", sub="North Dublin", exists=True,
  char="Clontarf is a mix of large red-brick Victorian and Edwardian houses along the seafront and the roads behind it, with 1930s semis further in around Vernon Avenue and Castle Avenue.",
  cond="Two problems dominate here. The seafront houses take salt and wind off the bay, and the mature trees along the inland roads drop enough leaf every autumn to block a gutter in a fortnight. A lot of the period houses also still have original cast iron.",
  nb=["Marino","Fairview","Raheny","Killester","Dollymount","Vernon Avenue","Castle Avenue","St Anne's","Clontarf Road"],
  revs=[("Original cast iron on a Victorian seafront house. They restored it rather than replacing it — exactly what we wanted.","Hugh B.","Clontarf Road"),
        ("Leaves off the road blocked us every October. Cleaning twice a year now and no more trouble.","Ann Marie G.","Vernon Avenue"),
        ("Big high roof, they had the right access gear and got it done safely.","Ciaran D.","Castle Avenue")]),
 dict(slug="raheny", name="Raheny", label="Dublin 5", sub="North Dublin", exists=True,
  char="Raheny runs from the older houses near the village and St Anne's out through the big 1950s and 60s estates around Watermill, Edenmore and Foxfield.",
  cond="St Anne's Park and the mature planting through the older estates mean serious leaf fall. Gutters here fill faster than almost anywhere on the northside, and a blocked gutter left through the winter is how water gets behind a fascia.",
  nb=["Clontarf","Kilbarrack","Donaghmede","Killester","Artane","Watermill","Edenmore","Foxfield","St Anne's"],
  revs=[("Water was getting in behind the fascia after a winter of blockages. Caught it before it did real damage.","Liam O.","Watermill"),
        ("Cleaned, flushed and checked the downpipes. Sent photos of the before and after, which I appreciated.","Deirdre F.","Foxfield"),
        ("Fair price for a full clean and a couple of small repairs. No upselling.","Mark H.","Raheny Village")]),
 dict(slug="kilbarrack", name="Kilbarrack", label="Dublin 5", sub="North Dublin",
  char="Kilbarrack is mostly 1960s and 70s local authority and private estate housing, running from the coast road back towards Greendale and Foxfield.",
  cond="Close enough to the sea for salt to matter, and old enough that most original gutter systems are well past their design life. Brittle, sun-damaged PVC that cracks the moment it's disturbed is the common find.",
  nb=["Raheny","Donaghmede","Baldoyle","Sutton","Greendale","Bayside","Foxfield","Kilbarrack Road","Howth Road"],
  revs=[("Old PVC snapped the second they touched it — replaced the run properly instead of bodging it.","Tony McC.","Greendale"),
        ("Straightforward job, straightforward price. Turned up when they said.","Sinead B.","Kilbarrack Road"),
        ("Sorted a leak that two other lads had failed to find.","Robert E.","Bayside")]),
 dict(slug="artane", name="Artane", label="Dublin 5", sub="North Dublin",
  char="Artane is dominated by large 1940s and 50s estates — long rows of semis around Kilmore, Brookwood and Ardlea, with the older houses closer to the village.",
  cond="These houses were built with narrow cast iron or early asbestos gutters, and where those haven't been changed they're now brittle and heavy. Replacing them with modern PVC usually costs less than repeatedly patching them.",
  nb=["Beaumont","Coolock","Raheny","Killester","Donnycarney","Kilmore","Ardlea","Brookwood","Harmonstown"],
  revs=[("Old gutters were cracked the length of the house. New PVC run, done in a day.","Frank D.","Ardlea"),
        ("Advised us to repair the back and only replace the front. Saved us a good bit.","Marie L.","Brookwood"),
        ("Polite lads, cleaned up everything before they left.","Gerry N.","Artane")]),
 dict(slug="beaumont", name="Beaumont", label="Dublin 9", sub="North Dublin",
  char="Beaumont is a settled residential area of 1950s to 70s semis and bungalows, with the hospital and the bigger roads around Shantalla and Collins Avenue running through it.",
  cond="Mature back gardens and street trees mean steady leaf and moss build-up. The other common issue is downpipes discharging straight onto a path or driveway, which we usually reroute properly into the drain.",
  nb=["Artane","Santry","Whitehall","Drumcondra","Coolock","Shantalla","Collins Avenue","Griffith Avenue","Donnycarney"],
  revs=[("Downpipe had been running onto the drive for years and cracked it. They rerouted it into the drain properly.","Catherine W.","Shantalla"),
        ("Moss build-up cleared and the whole system flushed. Good value.","Brendan K.","Collins Avenue"),
        ("Second time using them. Same standard both times.","Helen P.","Beaumont")]),
 dict(slug="santry", name="Santry", label="Dublin 9", sub="North Dublin",
  char="Santry mixes older housing near the village and Santry Demesne with big estates at Poppintree and Northwood, plus a lot of commercial and light industrial along the Swords Road.",
  cond="The commercial units around here have long box and valley gutters that need a completely different approach to a house. On the residential side it's the usual mix of blockages and tired 1960s systems.",
  nb=["Whitehall","Beaumont","Ballymun","Coolock","Northwood","Poppintree","Swords Road","Santry Demesne","Dublin Airport"],
  revs=[("Commercial unit with a box gutter that had been leaking for months. They knew exactly what they were looking at.","Operations Mgr","Swords Road"),
        ("House job — cleared, repaired a joint, gone in two hours.","Anthony R.","Santry Village"),
        ("Turned up for an emergency during a downpour. Fair play to them.","Jacqueline S.","Northwood")]),
 dict(slug="whitehall", name="Whitehall", label="Dublin 9", sub="North Dublin",
  char="Whitehall is classic 1930s and 40s Dublin — long, well-kept terraces and semis either side of Collins Avenue and the Swords Road, with big mature trees on most roads.",
  cond="The trees are the story here. Whitehall gutters block reliably every autumn, and because many of the houses still have their original narrow profiles they overflow at the front the moment they do.",
  nb=["Beaumont","Santry","Drumcondra","Glasnevin","Marino","Collins Avenue","Larkhill","Griffith Avenue","Swords Road"],
  revs=[("Every October without fail. Now they come before it starts and we've had no overflow since.","Padraig C.","Larkhill"),
        ("Original 1930s gutters finally gave up. New system fitted neatly, matched the neighbours.","Rosaleen M.","Whitehall"),
        ("Explained why it kept blocking rather than just clearing it again. Sorted the actual cause.","Eoin G.","Griffith Avenue")]),
 dict(slug="drumcondra", name="Drumcondra", label="Dublin 9", sub="North Dublin",
  char="Drumcondra is red-brick Victorian and Edwardian terraces around the Tolka and Griffith Avenue, with a lot of the larger houses now split into flats and student accommodation.",
  cond="Period terraces mean shared valley gutters and parapets between houses, and those are where the serious leaks start. Original cast iron is still common, and the mature trees along the river add a heavy autumn leaf load.",
  nb=["Glasnevin","Whitehall","Phibsborough","Marino","Fairview","Griffith Avenue","Tolka","Botanic Avenue","Clonliffe"],
  revs=[("Valley gutter between two houses was the source of a leak nobody could find. They traced it properly.","Sean T.","Botanic Avenue"),
        ("Cast iron repaired and repainted rather than replaced. Kept the look of the house.","Orla D.","Drumcondra Road"),
        ("Landlord here — they handle three of my properties now. Reliable.","Property Owner","Clonliffe")]),
 dict(slug="glasnevin", name="Glasnevin", label="Dublin 11", sub="North Dublin",
  char="Glasnevin covers the older red-brick roads near the Botanic Gardens, the big 1930s and 40s estates around Ballygall and Ballymun Road, and newer infill closer to DCU.",
  cond="With the Botanic Gardens and heavily planted older roads, leaf fall here is as bad as anywhere in the city. Add the shared valley gutters on the period terraces and there's plenty to keep an eye on.",
  nb=["Drumcondra","Finglas","Ballymun","Phibsborough","Cabra","Ballygall","Botanic Gardens","Griffith Avenue","Hampstead"],
  revs=[("Leaves off the Botanics every year. Two cleans a year and the problem's gone.","Nuala F.","Botanic Avenue"),
        ("Gutter had pulled away from a high gable. Rebracketed and resealed, no more damp inside.","Colm B.","Ballygall"),
        ("Quick, clean and reasonable. Would use again.","Aisling D.","Glasnevin")]),
 dict(slug="phibsborough", name="Phibsborough", label="Dublin 7", sub="North Dublin",
  char="Phibsborough is dense Victorian terraces around the canal and the North Circular Road, plus artisan cottages and a good deal of period property in multiple occupancy.",
  cond="Terraced streets mean gutters and downpipes shared with the house next door, and parapet gutters hidden behind the front wall where you can't see a problem until it's inside. These need inspecting, not guessing at.",
  nb=["Cabra","Glasnevin","Drumcondra","Stoneybatter","Broadstone","North Circular Road","Royal Canal","Grangegorman","Dorset Street"],
  revs=[("Hidden parapet gutter was the cause of damp in the return. Would never have found it myself.","Michael K.","North Circular Road"),
        ("Shared downpipe with next door. They dealt with both neighbours and got it sorted.","Grainne O.","Phibsborough"),
        ("Old cottage, awkward access, no fuss about it.","Dermot L.","Stoneybatter")]),
 dict(slug="cabra", name="Cabra", label="Dublin 7", sub="North Dublin",
  char="Cabra is largely 1930s and 40s corporation housing — long uniform terraces around the Navan Road, Fassaugh and Quarry Road, with newer infill scattered through.",
  cond="Original narrow gutters and cast iron downpipes are still in place on plenty of these houses. They're long past their best, and because the terraces are uniform, one failing run is usually a sign the neighbours are next.",
  nb=["Phibsborough","Navan Road","Ashtown","Finglas","Glasnevin","Fassaugh","Quarry Road","Broombridge","Ratoath Road"],
  revs=[("Original cast iron finally cracked. New PVC run front and back for a sensible price.","Willie M.","Fassaugh"),
        ("Did our house and two neighbours the same week. Good rate for the three.","Sandra J.","Quarry Road"),
        ("No mess, no drama, done in a day.","Thomas D.","Cabra")]),
 dict(slug="finglas", name="Finglas", label="Dublin 11", sub="North Dublin", exists=True,
  char="Finglas is mostly large 1950s and 60s estates — Finglas East, West and South — with the older village core and newer developments out towards Charlestown.",
  cond="Estate housing of this age is at the point where the original gutters have simply worn out. Sun-brittled PVC and rusted brackets are the norm, and we do more full replacements here than repairs.",
  nb=["Glasnevin","Ballymun","Cabra","Blanchardstown","Charlestown","Ballygall","Cappagh","Dunsink","Finglas Village"],
  revs=[("Original gutters were beyond repair. Honest about that, and the replacement price was fair.","Christy B.","Finglas East"),
        ("Rain was coming in over the front door for months. Fixed properly in one visit.","Lorraine K.","Cappagh"),
        ("Would recommend. Straight talking and good work.","Noel R.","Finglas West")]),
 dict(slug="ballymun", name="Ballymun", label="Dublin 9", sub="North Dublin",
  char="Ballymun has changed enormously — the towers are gone and most of the housing now is either regenerated low-rise from the last twenty years or the surviving older estates around Poppintree and Silloge.",
  cond="The newer builds are mostly fine but often have undersized downpipes for the roof area, which shows up as overflow in heavy rain. The older stock has the usual end-of-life issues.",
  nb=["Santry","Glasnevin","Finglas","Poppintree","Silloge","Shangan","Coultry","Northwood","Dublin City University"],
  revs=[("Newer house but the downpipe couldn't cope. Added a second one and the overflow stopped.","Karen M.","Poppintree"),
        ("Clear price up front, no changes at the end.","Derek O.","Silloge"),
        ("Quick response and a proper job.","Angela T.","Ballymun")]),
 dict(slug="coolock", name="Coolock", label="Dublin 17", sub="North Dublin",
  char="Coolock is a large area of 1960s and 70s estate housing around Bonnybrook, Darndale and Kilmore, with the older village and Cadbury's site at its centre.",
  cond="Uniform estates built at the same time now need the same work at the same time. Most of what we do here is full gutter, fascia and soffit replacement on systems that have done their fifty years.",
  nb=["Artane","Beaumont","Donaghmede","Santry","Bonnybrook","Darndale","Kilmore","Priorswood","Clonshaugh"],
  revs=[("Gutters, fascia and soffit all done together. Made sense to do it in one go and the price reflected that.","Martin H.","Bonnybrook"),
        ("They did four houses on our terrace. Neat work on all of them.","Elizabeth C.","Kilmore"),
        ("Sorted a bad leak the week before Christmas. Very obliging.","Damien F.","Coolock")]),
 dict(slug="marino", name="Marino", label="Dublin 3", sub="North Dublin",
  char="Marino is one of the best preserved early corporation schemes in the country — 1920s terraces laid out around Griffith Avenue and the Croydon estate, almost all to the same design.",
  cond="These are approaching a hundred years old and many still carry original or early-replacement cast iron. Access between the tight terraces takes care, and matching the profile matters if the row is to keep its look.",
  nb=["Fairview","Clontarf","Drumcondra","Whitehall","Croydon","Griffith Avenue","Philipsburgh","Donnycarney","Killester"],
  revs=[("Careful to match the profile so it didn't stand out from the rest of the terrace. That mattered to us.","Maura G.","Croydon Park"),
        ("Cast iron down the back, awkward access, handled it grand.","John Paul D.","Marino"),
        ("Honest quote and stuck to it.","Teresa B.","Philipsburgh")]),
 dict(slug="fairview", name="Fairview", label="Dublin 3", sub="North Dublin",
  char="Fairview is red-brick Victorian and Edwardian terraces around the park and Ballybough, a lot of it now flats and rented property, with the coast road running along the front.",
  cond="Period terraces close to the water: cast iron, parapet and valley gutters, salt in the air off the bay, and mature trees in the park. Between them there's rarely a dull inspection in Fairview.",
  nb=["Marino","Clontarf","Drumcondra","Ballybough","North Strand","East Wall","Fairview Park","Philipsburgh","Annesley"],
  revs=[("Leak into the top flat traced to a parapet gutter. Fixed once, properly.","Landlord","Fairview"),
        ("Old cast iron repaired where it could be, replaced where it couldn't. Sensible approach.","Cormac N.","Ballybough"),
        ("Reliable, and good at keeping tenants informed.","Property Manager","North Strand")]),
 dict(slug="blanchardstown", name="Blanchardstown", label="Dublin 15", sub="West Dublin", exists=True,
  char="Blanchardstown spreads from the old village across a huge area of estate housing — Corduff, Mulhuddart, Tyrrelstown and the newer developments around the shopping centre and Ongar.",
  cond="Dublin 15 has housing of every age within a couple of miles. The 1970s and 80s estates are at replacement stage; the newer builds tend to have fitting and sizing faults rather than worn-out gutters.",
  nb=["Castleknock","Clonsilla","Ongar","Mulhuddart","Corduff","Tyrrelstown","Coolmine","Blakestown","Hartstown"],
  revs=[("Newer house, gutters badly fitted by the builder. They refixed the whole run to a proper fall.","Wayne D.","Tyrrelstown"),
        ("Older estate, full replacement. Tidy and quick.","Bridget M.","Corduff"),
        ("Good price, showed up on time, no issues.","Shane K.","Blanchardstown")]),
 dict(slug="castleknock", name="Castleknock", label="Dublin 15", sub="West Dublin", exists=True,
  char="Castleknock is comfortable detached and semi-detached family housing around the village, Laurel Lodge and Diswellstown, with mature planting on most roads and the Phoenix Park on the doorstep.",
  cond="The trees are the main issue — large mature gardens and heavily planted roads drop a lot into gutters every autumn. The houses are generally well maintained, so it's more cleaning and preventative work than replacement.",
  nb=["Blanchardstown","Clonsilla","Ashtown","Navan Road","Laurel Lodge","Diswellstown","Carpenterstown","Porterstown","Phoenix Park"],
  revs=[("Annual clean and a check-over. Straightforward arrangement, they just get on with it.","Richard A.","Laurel Lodge"),
        ("Big house, high gutters, they had the right equipment. Felt safe having them here.","Miriam L.","Castleknock"),
        ("Repaired a joint rather than pushing a full replacement. Appreciated the honesty.","Alan McG.","Carpenterstown")]),
 dict(slug="clonsilla", name="Clonsilla", label="Dublin 15", sub="West Dublin",
  char="Clonsilla runs from the older houses near the church and station out through Hartstown, Huntstown and the newer estates towards Ongar and Littlepace.",
  cond="Most of the housing here is 1980s onwards, so the common jobs are worn brackets, joints that have opened up, and downpipes that were undersized for a three-storey roof from the day they went in.",
  nb=["Blanchardstown","Ongar","Castleknock","Hartstown","Huntstown","Littlepace","Coolmine","Porterstown","Clonee"],
  revs=[("Three-storey house, one downpipe doing the work of two. They added a second and it fixed it.","Gavin R.","Littlepace"),
        ("Joints had opened up all along the back. Resealed the run for a fair price.","Sharon B.","Hartstown"),
        ("On time and tidy. No complaints.","Vincent M.","Clonsilla")]),
 dict(slug="ongar", name="Ongar", label="Dublin 15", sub="West Dublin",
  char="Ongar is one of Dublin's newer suburbs — mostly 2000s townhouses, duplexes and apartments laid out around the village centre, with Littlepace and Hansfield alongside.",
  cond="Newer doesn't mean trouble-free. Tall narrow houses throw a lot of water into small gutters, and on many of these estates the original fitting was rushed. Poor falls and overloaded downpipes are what we see most.",
  nb=["Clonsilla","Blanchardstown","Littlepace","Hansfield","Clonee","Barnwell","Castaheany","Tyrrelstown","Dunboyne"],
  revs=[("Builder's gutters never had the right fall. Refitted properly and the pooling stopped.","Anita S.","Castaheany"),
        ("Duplex with awkward access. They managed it without any fuss.","Paul D.","Ongar Village"),
        ("Good communication from quote to finish.","Rachel T.","Hansfield")]),
 dict(slug="mulhuddart", name="Mulhuddart", label="Dublin 15", sub="West Dublin",
  char="Mulhuddart takes in the old village, the large estates at Ladyswell and Parslickstown, and a good deal of newer housing pushing out towards Tyrrelstown and Damastown.",
  cond="It's a mix of 1970s stock now needing replacement and 2000s housing needing refitting. Wind across the open ground towards Damastown is hard on brackets on the exposed sides.",
  nb=["Blanchardstown","Tyrrelstown","Ongar","Clonee","Ladyswell","Parslickstown","Damastown","Corduff","Church Road"],
  revs=[("Wind loosened the whole front run. Refixed with heavier brackets, no movement since.","Jason K.","Ladyswell"),
        ("Full replacement on a 70s semi. Fair price and done in a day.","Bernie O.","Mulhuddart"),
        ("Turned up when they said they would, which is half the battle.","Ade A.","Parslickstown")]),
 dict(slug="dunboyne", name="Dunboyne", label="Co. Meath", sub="North West Commuter Belt", exists=True,
  char="Dunboyne has an old village core with a great deal of 2000s estate housing built around it, plus larger detached houses and bungalows on the roads out towards Clonee and Summerhill.",
  cond="Open Meath countryside on three sides means wind-driven rain hits gutters hard here. On the newer estates it's fitting quality; on the older village houses and bungalows it's genuinely worn-out systems.",
  nb=["Clonee","Ongar","Blanchardstown","Ratoath","Summerhill","Castaheany","Pace","Rooske","Maynooth"],
  revs=[("Wind and rain off the fields had the gutters overflowing at the gable. Sorted with a bigger downpipe.","Nigel W.","Dunboyne"),
        ("Bungalow on the Summerhill road. Full new gutters, fascia and soffit. Delighted.","Kathleen M.","Rooske"),
        ("Came out from Dublin without charging extra for the distance.","Fergal D.","Pace")]),
 dict(slug="city-centre", name="Dublin City Centre", label="Dublin 1 & 2", sub="Dublin City Centre", exists=True,
  char="The city centre is Georgian terraces, Victorian commercial buildings and modern apartment blocks, much of it protected structures and almost all of it terraced or shared.",
  cond="Almost nothing here is a simple pitched roof with a gutter on the front. It's parapet gutters, valley gutters, hoppers and cast iron downpipes running down shared party walls — work that needs proper access equipment and someone who has done it before.",
  nb=["Phibsborough","Fairview","Ballsbridge","Ringsend","Smithfield","Stoneybatter","The Liberties","Docklands","Grand Canal"],
  revs=[("Georgian building, parapet gutter, protected structure. They knew what they were dealing with.","Building Manager","Dublin 2"),
        ("Cast iron downpipe on a shared wall. Coordinated with the neighbouring owner and got it done.","Owner","Dublin 1"),
        ("Proper access equipment and full insurance paperwork without me having to ask.","Facilities Mgr","Docklands")]),
]
