# -*- coding: utf-8 -*-
SOUTH = [
 dict(slug="dun-laoghaire", name="Dún Laoghaire", label="Co. Dublin", sub="South Dublin",
  char="Dún Laoghaire is Victorian terraces and large period houses stepping back from the harbour, with 1930s semis further in and a lot of apartment conversions near the seafront.",
  cond="Salt air off the harbour is relentless on metal fixings, and the tall period houses have parapet and valley gutters that hide a leak until it reaches a ceiling. Original cast iron is still common here.",
  nb=["Glenageary","Monkstown","Sandycove","Dalkey","Blackrock","Glasthule","Sallynoggin","Deansgrange","Killiney"],
  revs=[("Cast iron on a Victorian terrace facing the sea. Restored what they could and matched the rest.","Peadar C.","Sandycove"),
        ("Parapet gutter leak that had been damaging a ceiling for months. Found and fixed in one visit.","Elaine R.","Dún Laoghaire"),
        ("Salt had destroyed the brackets. Stainless replacements this time — should outlast me.","Brian K.","Glasthule")]),
 dict(slug="dalkey", name="Dalkey", label="Co. Dublin", sub="South Dublin",
  char="Dalkey runs from the village up the hill towards Killiney, with granite period houses, coastal villas and a lot of individually designed modern homes on the steeper roads.",
  cond="Exposed hillside, salt air and steep or unusual roof shapes. Very few gutter runs in Dalkey are a simple straight line, so this is measure-and-make-to-fit work rather than off-the-shelf.",
  nb=["Killiney","Glenageary","Sandycove","Dún Laoghaire","Ballsbridge","Coliemore","Bulloch","Sorrento","Dalkey Village"],
  revs=[("Awkward roof, nothing standard about it. They measured properly and it fits perfectly.","Hilary M.","Sorrento Road"),
        ("Granite period house — careful, respectful work. No damage to the stone.","Andrew P.","Dalkey Village"),
        ("Exposed spot up the hill. Heavier brackets made all the difference.","Fiona S.","Coliemore")]),
 dict(slug="killiney", name="Killiney", label="Co. Dublin", sub="South Dublin",
  char="Killiney is large detached houses on generous sites along the hill and the coast road, ranging from Victorian villas to substantial modern builds.",
  cond="Big houses mean long gutter runs, multiple downpipes and often more than one roof level draining into the same system. Add hillside exposure and heavy mature planting and there's a lot that can go wrong quietly.",
  nb=["Dalkey","Ballybrack","Shankill","Glenageary","Cabinteely","Killiney Hill","Killiney Bay","Ballinclea","Foxrock"],
  revs=[("Two roof levels draining into one undersized downpipe. They redesigned it properly.","Jonathan H.","Killiney Hill"),
        ("Long runs, big house, done without fuss over three days.","Patricia L.","Killiney Bay"),
        ("Mature trees everywhere. They set us up on a twice-yearly clean.","Robert F.","Ballinclea")]),
 dict(slug="glenageary", name="Glenageary", label="Co. Dublin", sub="South Dublin",
  char="Glenageary is comfortable 1930s to 1960s detached and semi-detached family housing on wide, well-planted roads between Dún Laoghaire and Killiney.",
  cond="Mature gardens on every road mean steady leaf load, and enough of the housing is now sixty-plus years old that original systems are failing. Close enough to the coast for salt to shorten bracket life too.",
  nb=["Dún Laoghaire","Killiney","Sallynoggin","Dalkey","Deansgrange","Glenageary Road","Silchester","Honeypark","Sandycove"],
  revs=[("Sixty-year-old gutters, well past it. Replaced front and back, neat job.","Valerie D.","Silchester"),
        ("Twice-yearly clean sorted. No more overflowing at the porch.","Gerard M.","Glenageary Road"),
        ("Fair quote, no surprises at the end.","Susan O.","Honeypark")]),
 dict(slug="monkstown", name="Monkstown", label="Co. Dublin", sub="South Dublin",
  char="Monkstown is one of the finest period areas in Dublin — Victorian and Regency terraces, granite villas and squares around the church, with a lot of protected structures.",
  cond="Period and protected buildings need sympathetic work: parapet gutters behind decorative stonework, original cast iron and hopper heads, and shared valleys between terraced houses. This isn't a job for a ladder and a tube of sealant.",
  nb=["Blackrock","Dún Laoghaire","Salthill","Seapoint","Booterstown","Deansgrange","Monkstown Village","Newtownpark","Stradbrook"],
  revs=[("Protected structure. They understood the constraints and worked with them.","Owner","Monkstown Village"),
        ("Original hopper head kept and reused. Delighted they didn't just bin it.","Anne Marie G.","Seapoint"),
        ("Shared valley with next door — dealt with both sides properly.","Colin B.","Stradbrook")]),
 dict(slug="blackrock", name="Blackrock", label="Co. Dublin", sub="South Dublin", exists=True,
  char="Blackrock has period houses near the village and the seafront, big 1930s and 50s semis through Newtownpark and Temple Road, and newer apartment developments closer to the town centre.",
  cond="Coastal salt plus a lot of mature planting inland. The period stock has cast iron and parapet gutters; the mid-century semis are now at the age where original systems give out.",
  nb=["Monkstown","Booterstown","Stillorgan","Mount Merrion","Deansgrange","Newtownpark","Temple Road","Rock Road","Frascati"],
  revs=[("Original gutters on a 1930s semi finally went. Replaced properly, matched the neighbours.","Denis W.","Newtownpark"),
        ("Seafront house, salt damage on all the fixings. Stainless throughout this time.","Caroline T.","Rock Road"),
        ("Good advice, no pressure, decent price.","Martin S.","Temple Road")]),
 dict(slug="booterstown", name="Booterstown", label="Co. Dublin", sub="South Dublin",
  char="Booterstown is period terraces and villas along the Rock Road and the avenue, with 1950s and 60s housing behind and the marsh and coast in front.",
  cond="Right on the bay, so salt and wind are constant, and the older houses carry the usual period complications of parapets, valleys and cast iron. The marsh side also brings a lot of bird activity into gutters.",
  nb=["Blackrock","Mount Merrion","Donnybrook","Ballsbridge","Stillorgan","Booterstown Avenue","Rock Road","Cross Avenue","Sydney Parade"],
  revs=[("Nesting birds in the gutter every spring. Guards fitted and that was the end of it.","Josephine E.","Booterstown Avenue"),
        ("Period house, careful work on the cast iron. Very happy.","Nicholas R.","Cross Avenue"),
        ("Prompt, insured, tidy. Everything you want.","Yvonne D.","Rock Road")]),
 dict(slug="mount-merrion", name="Mount Merrion", label="Co. Dublin", sub="South Dublin",
  char="Mount Merrion is a planned 1940s and 50s suburb — well-built semis and detached houses on curving, heavily planted roads around the Rise, the Park and Deerpark.",
  cond="The tree cover here is exceptional and so is the autumn leaf load. Most houses are on their second gutter system by now, and the ones that aren't are due. Gutter guards genuinely earn their keep in Mount Merrion.",
  nb=["Stillorgan","Booterstown","Blackrock","Goatstown","Clonskeagh","Deerpark","The Rise","Trees Road","Wilson Road"],
  revs=[("Leaves were beating us every year. Guards fitted and the difference is night and day.","Frank O'N.","The Rise"),
        ("Second set of gutters in seventy years. Fitted well, tidy job.","Maeve C.","Trees Road"),
        ("Explained the options clearly and let us decide. No hard sell.","Declan B.","Deerpark")]),
 dict(slug="stillorgan", name="Stillorgan", label="Co. Dublin", sub="South Dublin", exists=True,
  char="Stillorgan mixes 1950s and 60s estate housing around the village and Kilmacud with larger detached homes towards Mount Merrion and newer apartments near the shopping centre.",
  cond="Mid-century estates now at replacement age, plenty of mature planting, and a good deal of commercial property along the Lower Kilmacud Road that needs a different approach again.",
  nb=["Mount Merrion","Blackrock","Sandyford","Dundrum","Goatstown","Kilmacud","Leopardstown","Newtownpark","Galloping Green"],
  revs=[("1960s house, original gutters. Replaced the lot and it looks great.","Eileen H.","Kilmacud"),
        ("Commercial unit on the Lower Kilmacud Road. Handled it professionally.","Owner","Stillorgan"),
        ("Reasonable price and they stuck to it.","Aidan M.","Galloping Green")]),
 dict(slug="dundrum", name="Dundrum", label="Dublin 14", sub="South Dublin",
  char="Dundrum runs from the old village out through 1950s and 60s estates at Ballinteer Road and Sydenham, with a lot of newer apartment development around the town centre and Sandyford Road.",
  cond="Older estate housing at replacement age sits alongside modern apartment blocks with communal gutters and box sections. Two very different types of work within the same postcode.",
  nb=["Ballinteer","Sandyford","Goatstown","Churchtown","Windy Arbour","Balally","Taney","Milltown","Clonskeagh"],
  revs=[("1960s semi, gutters gone. New system front and back in a day.","Rosemary K.","Sydenham"),
        ("Apartment block roof gutters. They dealt with the management company directly.","Management Co.","Dundrum"),
        ("Quick, clean and well priced.","Tomás F.","Balally")]),
 dict(slug="rathmines", name="Rathmines", label="Dublin 6", sub="South Dublin",
  char="Rathmines is dense Victorian and Edwardian red-brick, much of it converted to flats, running from the canal down to Rathgar with tree-lined roads throughout.",
  cond="Converted period houses are the challenge here — multiple occupiers, shared downpipes, parapet gutters hidden behind the front parapet, and heavy leaf fall from the street trees. Leaks are rarely where the damp appears.",
  nb=["Ranelagh","Rathgar","Harold's Cross","Portobello","Terenure","Milltown","Kenilworth","Leinster Road","Grove Park"],
  revs=[("Damp in a top-floor flat, source was a parapet gutter two rooms away. They traced it properly.","Landlord","Leinster Road"),
        ("Shared downpipe with next door. They sorted the neighbour side too.","Aoibhinn D.","Kenilworth"),
        ("Manage several properties here — reliable and good with tenants.","Property Manager","Rathmines")]),
 dict(slug="ranelagh", name="Ranelagh", label="Dublin 6", sub="South Dublin",
  char="Ranelagh is Victorian terraces and artisan cottages around the village and the canal, with larger period houses on Sandford Road and Marlborough Road.",
  cond="Tight terraced streets, shared valleys, cast iron downpipes on party walls and very mature trees. Access is often the hardest part of a Ranelagh job, and it's why proper equipment matters more than a long ladder.",
  nb=["Rathmines","Donnybrook","Milltown","Portobello","Rathgar","Sandford Road","Marlborough Road","Beechwood","Cullenswood"],
  revs=[("Artisan cottage, no side access at all. They worked it out and got it done.","Sorcha N.","Cullenswood"),
        ("Cast iron on a shared wall, handled with the neighbours. No arguments.","Ruairi M.","Beechwood"),
        ("Careful around the garden and cleaned up fully.","Isabel W.","Sandford Road")]),
 dict(slug="rathgar", name="Rathgar", label="Dublin 6", sub="South Dublin",
  char="Rathgar is large Victorian red-brick houses on wide, heavily planted roads, many of them still single family homes and a good number of them protected.",
  cond="Big houses, high roofs, original cast iron and some of the heaviest leaf fall in the city off the mature street planting. These are jobs where the right access equipment is the difference between a proper repair and a bodge.",
  nb=["Rathmines","Terenure","Harold's Cross","Milltown","Churchtown","Orwell","Highfield","Brighton Road","Garville"],
  revs=[("Very high gutters at the back. They had the access gear and did it safely.","Charles D.","Orwell Road"),
        ("Original cast iron restored rather than replaced. Kept the character of the house.","Philippa G.","Garville"),
        ("Leaf fall here is unreal. Two visits a year now sorts it.","Hugh McD.","Brighton Road")]),
 dict(slug="terenure", name="Terenure", label="Dublin 6W", sub="South Dublin",
  char="Terenure has Victorian and Edwardian houses near the village and along Terenure Road, with big 1930s to 50s semis through Bushy Park, Fortfield and Greenlea.",
  cond="Bushy Park and the mature roads around it mean serious autumn leaf load. The 1930s semis are largely on original or first-replacement gutters, and many still have narrow profiles that overflow in a downpour.",
  nb=["Rathgar","Templeogue","Harold's Cross","Kimmage","Rathfarnham","Bushy Park","Fortfield","Greenlea","Brighton Square"],
  revs=[("Bushy Park leaves every autumn. They come before it starts now.","Miriam T.","Fortfield"),
        ("Narrow old gutters replaced with a bigger profile. No more overflow.","Seamus B.","Greenlea"),
        ("Straightforward and honest to deal with.","Grace L.","Terenure")]),
 dict(slug="templeogue", name="Templeogue", label="Dublin 6W", sub="South West Dublin",
  char="Templeogue is largely 1950s to 70s semis and detached housing around Templeville Road, Cypress and Orwell Park, with the older village at its heart.",
  cond="Housing of this era is now on borrowed time gutter-wise, and the mature planting through the estates adds a steady leaf load. Fascia and soffit replacement usually goes hand in hand with the gutters here.",
  nb=["Terenure","Rathfarnham","Knocklyon","Firhouse","Tallaght","Orwell Park","Cypress","Templeville","Fortfield"],
  revs=[("Did gutters, fascia and soffit in one go. Made sense and the price was right.","Pauline R.","Orwell Park"),
        ("70s house, everything original until now. Big improvement.","Barry K.","Cypress Grove"),
        ("Neat, quick and well mannered.","Nora D.","Templeogue")]),
 dict(slug="rathfarnham", name="Rathfarnham", label="Dublin 14", sub="South Dublin",
  char="Rathfarnham runs from the old village up towards the mountains, taking in period houses near the castle, big 1960s and 70s estates at Butterfield and Ballyroan, and larger homes on the higher ground.",
  cond="The closer you get to the mountains the more weather you catch — wind-driven rain off the higher ground is hard on gutters at Ballyboden and Edmondstown. Lower down it's leaf fall and end-of-life estate systems.",
  nb=["Templeogue","Knocklyon","Ballyboden","Churchtown","Terenure","Butterfield","Ballyroan","Edmondstown","Grange"],
  revs=[("Up near the mountains the rain comes sideways. Bigger gutters and an extra downpipe fixed it.","Colm H.","Edmondstown"),
        ("70s estate house, full replacement. Tidy work, fair price.","Bernadette O.","Ballyroan"),
        ("Came out same day for storm damage. Very grateful.","Peter M.","Butterfield")]),
 dict(slug="knocklyon", name="Knocklyon", label="Dublin 16", sub="South West Dublin",
  char="Knocklyon is almost entirely 1970s and 80s estate housing — Templeroan, Woodstown, Idrone and the roads around them, built out over a couple of decades to similar patterns.",
  cond="An estate built in one go reaches the end of its gutter life in one go. We're doing a lot of full replacements here, and because the houses match, neighbours often go in together on a price.",
  nb=["Firhouse","Rathfarnham","Ballinteer","Templeogue","Templeroan","Woodstown","Idrone","Ballycullen","Scholarstown"],
  revs=[("Three houses on our road did it the same week. Good rate for doing them together.","Trevor A.","Templeroan"),
        ("Original 1980s gutters, brittle as anything. All replaced in a day.","Sinéad K.","Woodstown"),
        ("No mess left behind, which I always worry about.","Máire F.","Idrone")]),
 dict(slug="firhouse", name="Firhouse", label="Dublin 24", sub="South West Dublin",
  char="Firhouse is 1970s and 80s estate housing between the Dodder and the Tallaght bypass, with newer development at Ballycullen and Old Court and the older village at Firhouse Road.",
  cond="Close to the mountains and the open ground along the Dodder, so wind is a factor, and the estate housing is at the age where brackets, joints and the gutters themselves are all giving out together.",
  nb=["Tallaght","Knocklyon","Templeogue","Ballycullen","Old Bawn","Oldcourt","Ballycragh","Dodder Valley","Bohernabreena"],
  revs=[("Wind had the front run hanging off. Refixed with proper brackets and it's solid.","Gerry W.","Oldcourt"),
        ("Full replacement, done in a day, no fuss.","Linda M.","Ballycullen"),
        ("Honest about what needed doing and what didn't.","Alan D.","Firhouse")]),
 dict(slug="ballinteer", name="Ballinteer", label="Dublin 16", sub="South Dublin",
  char="Ballinteer is 1970s and 80s estates — Broadford, Meadowmount, Woodpark — laid out on the rising ground between Dundrum and the mountains.",
  cond="The ground rises towards Ticknock and the exposure increases with it. Combine that with estate gutters now forty-odd years old and you get a lot of storm-damage call-outs every winter.",
  nb=["Dundrum","Knocklyon","Sandyford","Rathfarnham","Broadford","Meadowmount","Woodpark","Ticknock","Marley"],
  revs=[("Storm took a section off. Out the next day and made safe immediately.","Ruth B.","Broadford"),
        ("Forty-year-old gutters, all replaced. Should see us out.","Michael G.","Meadowmount"),
        ("Good clear quote, no add-ons afterwards.","Karen L.","Woodpark")]),
 dict(slug="sandyford", name="Sandyford", label="Dublin 18", sub="South Dublin",
  char="Sandyford is two things at once — the old village and its surrounding housing, and the business district with its office blocks, apartment towers and industrial units.",
  cond="The commercial side means large flat roofs, box gutters and internal rainwater outlets — a completely different discipline to a house gutter. On the residential side it's mostly newer housing with fitting and sizing issues.",
  nb=["Stillorgan","Dundrum","Leopardstown","Ballinteer","Stepaside","Kilgobbin","Balally","Central Park","Carrickmines"],
  revs=[("Office block box gutter overflowing into the car park. They diagnosed and fixed it properly.","Facilities Mgr","Sandyford Business District"),
        ("Apartment block communal gutters. Dealt with the management company throughout.","Management Co.","Central Park"),
        ("House job — quick, clean, well priced.","Owen T.","Sandyford Village")]),
 dict(slug="leopardstown", name="Leopardstown", label="Dublin 18", sub="South Dublin",
  char="Leopardstown is mostly newer housing and apartment development around the racecourse and the Ballyogan Road, alongside offices and retail near the M50.",
  cond="Modern three-storey houses and duplexes throw a lot of water into relatively small gutters, and the original fitting on some of these estates was rushed. Falls, joints and undersized downpipes are the usual finds.",
  nb=["Sandyford","Foxrock","Carrickmines","Stepaside","Cabinteely","Ballyogan","The Gallops","Brewery Road","Leopardstown Road"],
  revs=[("Three-storey townhouse with one downpipe. Added a second and the overflow stopped.","Jenny R.","The Gallops"),
        ("Builder's fall was wrong from day one. Refitted the run correctly.","David A.","Ballyogan"),
        ("Prompt and professional.","Ciara N.","Leopardstown Road")]),
 dict(slug="foxrock", name="Foxrock", label="Dublin 18", sub="South Dublin",
  char="Foxrock is large detached houses on big, heavily planted sites — Victorian and Edwardian villas near the village alongside substantial mid-century and modern homes.",
  cond="Large houses with long runs, multiple roof levels and mature trees on every boundary. Nothing here is a quick ladder job; it's proper access, proper measuring and usually more than one downpipe.",
  nb=["Cabinteely","Leopardstown","Deansgrange","Carrickmines","Stillorgan","Torquay Road","Westminster Road","Brighton Road","Kill Lane"],
  revs=[("Three roof levels feeding one system. They redesigned the drainage and it works.","Anthony B.","Torquay Road"),
        ("Mature trees all round. On a twice-yearly clean now and no more blockages.","Geraldine H.","Westminster Road"),
        ("Discreet, tidy and thorough. Exactly what we wanted.","Stephen McC.","Kill Lane")]),
 dict(slug="cabinteely", name="Cabinteely", label="Dublin 18", sub="South Dublin",
  char="Cabinteely has the old village, 1960s and 70s estates around Johnstown and Cornelscourt, and larger houses on the roads towards Foxrock and Killiney.",
  cond="Estate housing now well past forty years, with the added factor of mature planting through Cabinteely Park and the older gardens. Full replacements and twice-yearly cleaning are the two things we do most here.",
  nb=["Foxrock","Killiney","Ballybrack","Deansgrange","Shankill","Johnstown","Cornelscourt","Kill O' The Grange","Old Bray Road"],
  revs=[("70s estate, gutters finally beyond patching. Replaced neatly and quickly.","Marian D.","Johnstown"),
        ("Park trees mean constant leaves. Twice a year sorts it.","Kieran O.","Cornelscourt"),
        ("Reliable crowd, second job we've had done.","Sarah B.","Cabinteely")]),
 dict(slug="shankill", name="Shankill", label="Co. Dublin", sub="South Dublin",
  char="Shankill is a mix of older village housing, 1970s estates at Shanganagh and Corbawn, and newer development towards Woodbrook and the Bray border.",
  cond="It's the most exposed corner of south Dublin — open to the sea at Shanganagh and to the wind coming round Bray Head. Bracket failure and storm damage are far more common here than a few miles inland.",
  nb=["Ballybrack","Cabinteely","Killiney","Bray","Loughlinstown","Corbawn","Shanganagh","Woodbrook","Rathmichael"],
  revs=[("Wind off the sea had the whole run loose. Heavier fixings and it hasn't budged.","Noel B.","Corbawn"),
        ("Storm damage, out the same day to make it safe.","Fidelma K.","Shanganagh"),
        ("Fair price and a proper job.","James R.","Shankill")]),
 dict(slug="donnybrook", name="Donnybrook", label="Dublin 4", sub="South Dublin",
  char="Donnybrook is period red-brick terraces and large Victorian houses around the village, Morehampton Road and Marlborough Road, many of them protected or converted.",
  cond="Tall period houses with parapet gutters, hidden valleys and original cast iron. The trees along Morehampton and Ailesbury are heavy shedders, and a blocked parapet gutter on a house this tall causes real damage fast.",
  nb=["Ballsbridge","Ranelagh","Clonskeagh","Milltown","Sandymount","Morehampton","Ailesbury","Belmont","Eglinton"],
  revs=[("Parapet gutter blocked and water came through a bedroom ceiling. Fixed and now maintained yearly.","Fergus D.","Morehampton Road"),
        ("Protected structure, sympathetic work on the cast iron.","Owner","Ailesbury Road"),
        ("Very professional from quote to finish.","Lucy H.","Eglinton Road")]),
 dict(slug="ballsbridge", name="Ballsbridge", label="Dublin 4", sub="South Dublin",
  char="Ballsbridge is grand Victorian terraces and detached period houses around the embassies, with a good deal of office and institutional property and newer apartment development.",
  cond="Period residential and substantial commercial side by side. Parapet gutters, hopper heads, cast iron on party walls, and on the commercial buildings box gutters and internal outlets that need scheduled maintenance rather than reactive fixes.",
  nb=["Donnybrook","Sandymount","Ringsend","Booterstown","Merrion","Pembroke Road","Shelbourne Road","Herbert Park","Lansdowne"],
  revs=[("Office building with an internal outlet that kept backing up. Now on a maintenance schedule.","Facilities Mgr","Pembroke Road"),
        ("Period house, original hoppers kept and repaired. Excellent work.","Owner","Herbert Park"),
        ("Insured, professional and good paperwork. Made our compliance easy.","Building Manager","Lansdowne Road")]),
 dict(slug="sandymount", name="Sandymount", label="Dublin 4", sub="South Dublin",
  char="Sandymount is Victorian terraces and cottages around the green and the strand, with larger period houses on Sandymount Avenue and newer apartments near the coast.",
  cond="Directly on the bay, so salt and onshore wind attack fixings continually, and gulls nest in valley gutters every spring. The terraces bring the usual shared downpipes and parapets on top of that.",
  nb=["Ringsend","Ballsbridge","Irishtown","Donnybrook","Merrion","Sandymount Green","Strand Road","Tritonville","Beach Road"],
  revs=[("Gulls nested in the valley every year. Guards fitted and that was the end of it.","Órla K.","Strand Road"),
        ("Salt had rotted every bracket. Stainless throughout now.","Diarmuid F.","Beach Road"),
        ("Careful work on an old terrace. Very tidy.","Helen A.","Sandymount Green")]),
 dict(slug="ringsend", name="Ringsend", label="Dublin 4", sub="South Dublin",
  char="Ringsend and Irishtown are tight artisan terraces and cottages near the river, with the newer Docklands apartment blocks rising immediately alongside.",
  cond="Small old houses with shared downpipes and almost no side access, next door to modern blocks with communal roof drainage. Two completely different jobs on the same street, and the wind off the river affects both.",
  nb=["Irishtown","Sandymount","Ballsbridge","Docklands","Grand Canal","Pearse Street","Thorncastle","Bath Avenue","Cambridge Road"],
  revs=[("Cottage with no side access. They worked around it without complaint.","Paddy M.","Thorncastle Street"),
        ("Apartment block roof drainage. Dealt with the management company start to finish.","Management Co.","Grand Canal Dock"),
        ("Quick response and a fair price.","Sheila D.","Irishtown")]),
 dict(slug="milltown", name="Milltown", label="Dublin 6", sub="South Dublin",
  char="Milltown sits along the Dodder between Ranelagh and Dundrum — period houses near the river, 1930s and 50s semis on the higher roads and newer apartments near the Luas.",
  cond="The Dodder valley planting is heavy and the river brings damp air with it. Gutters on the valley side hold moss and silt far more than you'd expect, and blocked downpipes are the common call.",
  nb=["Ranelagh","Clonskeagh","Dundrum","Rathgar","Churchtown","Dartry","Windy Arbour","Dodder","Richmond Avenue"],
  revs=[("Downpipe silted up completely. Cleared and flushed, sorted in an hour.","Conor N.","Dartry"),
        ("Moss build-up on the river side every year. Regular clean now.","Aoife M.","Milltown"),
        ("Reliable and easy to deal with.","Barry O.","Windy Arbour")]),
 dict(slug="clonskeagh", name="Clonskeagh", label="Dublin 14", sub="South Dublin",
  char="Clonskeagh mixes period houses along the Dodder and Roebuck with 1950s and 60s semis around Bird Avenue and newer development near UCD.",
  cond="Very heavily planted, with the Dodder on one side and the UCD grounds on the other. Leaf load here is among the worst in the city, and a lot of the mid-century housing is on its original gutters still.",
  nb=["Milltown","Donnybrook","Goatstown","Dundrum","Windy Arbour","Roebuck","Bird Avenue","Farranboley","Belfield"],
  revs=[("Leaves from every direction. Twice-yearly clean has ended the overflowing.","Nuala B.","Bird Avenue"),
        ("Original 1950s gutters replaced. Long overdue and well done.","Terence H.","Roebuck"),
        ("Good honest advice about what actually needed doing.","Maria C.","Clonskeagh")]),
 dict(slug="goatstown", name="Goatstown", label="Dublin 14", sub="South Dublin",
  char="Goatstown is settled 1950s to 70s semis and detached housing between Dundrum and Clonskeagh, on well-planted roads around Goatstown Road and Drummartin.",
  cond="Mid-century housing now needing its second gutter system, with steady leaf load off mature gardens. Fascia and soffit are often as tired as the gutters by the time we're called.",
  nb=["Clonskeagh","Dundrum","Mount Merrion","Stillorgan","Windy Arbour","Drummartin","Farranboley","Taney","Balally"],
  revs=[("Gutters, fascia and soffit all replaced together. House looks transformed.","Patrick L.","Drummartin"),
        ("Second system in sixty years. Fitted well and neatly.","Angela R.","Goatstown Road"),
        ("Fair, quick and clean.","Donal F.","Taney")]),
 dict(slug="churchtown", name="Churchtown", label="Dublin 14", sub="South Dublin",
  char="Churchtown is 1940s to 60s semis and terraces around Braemor and Landscape, with larger period houses towards Dartry and newer infill near the Luas.",
  cond="Well-established gardens and street trees, and housing of an age where original gutters have either been replaced once or are badly overdue. Straightforward work, mostly, but plenty of it.",
  nb=["Rathgar","Milltown","Dundrum","Terenure","Windy Arbour","Braemor","Landscape","Dartry","Nutgrove"],
  revs=[("Original gutters, sixty years old. Replaced front and back in a day.","Kathleen S.","Braemor"),
        ("Cleaned, checked and repaired a couple of joints. Sensible approach.","Ronan D.","Landscape"),
        ("No pressure, no upselling. Refreshing.","Emer K.","Churchtown")]),
 dict(slug="harolds-cross", name="Harold's Cross", label="Dublin 6W", sub="South Dublin",
  char="Harold's Cross is Victorian terraces and artisan cottages along the canal and the green, with 1930s and 50s housing on the roads behind.",
  cond="Terraced streets mean shared valleys and downpipes, and the older cottages have very small original gutters. The canal-side planting adds a heavy leaf load every autumn on top.",
  nb=["Rathmines","Terenure","Kimmage","Portobello","Rathgar","Mount Argus","Grand Canal","Greenmount","Kenilworth"],
  revs=[("Shared valley between two cottages. They sorted both sides properly.","Paul N.","Greenmount"),
        ("Tiny original gutters replaced with something that can actually cope.","Bridie M.","Mount Argus"),
        ("Very tidy on a tight street. No bother to anyone.","Eoghan T.","Harold's Cross")]),
 dict(slug="kimmage", name="Kimmage", label="Dublin 12", sub="South West Dublin",
  char="Kimmage is largely 1930s to 50s corporation and private housing — long uniform terraces and semis around Sundrive, Ravensdale and the Kimmage Road.",
  cond="Original narrow gutters and cast iron downpipes still survive on a lot of these houses, and they're now brittle and heavy. Because the terraces are identical, when one house needs doing the neighbours usually do too.",
  nb=["Crumlin","Terenure","Harold's Cross","Walkinstown","Kimmage Road","Sundrive","Ravensdale","Larkfield","Kimmage Manor"],
  revs=[("Original cast iron cracked right through. New PVC and it's a different house in the rain.","Jimmy B.","Sundrive"),
        ("Did ours and the two next door. Good price for the three.","Rita C.","Ravensdale"),
        ("In and out in a day, no mess.","Alan H.","Kimmage")]),
 dict(slug="crumlin", name="Crumlin", label="Dublin 12", sub="South West Dublin",
  char="Crumlin is one of the great 1930s and 40s corporation schemes — mile after mile of uniform terraces and semis around Captain's Road, Clogher and the Crumlin Road.",
  cond="Almost all built at once, and a great many still have original or early narrow gutters. They're undersized for modern rainfall and brittle with age. Replacement rather than repair is usually the honest answer here.",
  nb=["Kimmage","Drimnagh","Walkinstown","Terenure","Captain's Road","Clogher Road","Windmill","Sundrive","Kildare Road"],
  revs=[("Old gutters overflowed every heavy shower. Bigger profile fitted and that was that.","Christy N.","Captain's Road"),
        ("Straight talking — told us replacement was the sensible option and why.","Marie D.","Kildare Road"),
        ("Good work, fair money, no messing.","Tony R.","Crumlin")]),
 dict(slug="drimnagh", name="Drimnagh", label="Dublin 12", sub="South West Dublin",
  char="Drimnagh is 1930s and 40s terraces and semis laid out between the canal and the Long Mile Road, with newer infill and some industrial property along the edges.",
  cond="Same story as its neighbours — uniform housing of the same age, original narrow gutters and cast iron downpipes coming to the end together. The canal-side roads also carry a fair leaf load.",
  nb=["Crumlin","Walkinstown","Inchicore","Bluebell","Long Mile Road","Grand Canal","Mourne Road","Galtymore","Errigal"],
  revs=[("Cast iron downpipe cracked and was soaking the wall. Replaced and the damp is gone.","Sean F.","Mourne Road"),
        ("Full replacement, done in a day, tidy job.","Philomena K.","Galtymore"),
        ("Honest quote and they stuck to it exactly.","Gary M.","Drimnagh")]),
 dict(slug="walkinstown", name="Walkinstown", label="Dublin 12", sub="South West Dublin",
  char="Walkinstown is 1950s housing around the roundabout and Cromwellsfort, with a good deal of light industrial and commercial property along the Long Mile and Greenhills Roads.",
  cond="Residential systems now seventy years old sit alongside a lot of commercial units with box and valley gutters. The industrial roofs here need scheduled clearing, not reactive call-outs.",
  nb=["Crumlin","Drimnagh","Greenhills","Kimmage","Bluebell","Cromwellsfort","Long Mile Road","Greenhills Road","Ballymount"],
  revs=[("Industrial unit, valley gutter overflowing into the warehouse. Cleared and repaired properly.","Site Manager","Ballymount"),
        ("House job, original 1950s gutters replaced. Great job.","Nuala P.","Cromwellsfort"),
        ("Reliable for both our units now.","Owner","Long Mile Road")]),
 dict(slug="clondalkin", name="Clondalkin", label="Dublin 22", sub="South West Dublin",
  char="Clondalkin has the old village and round tower at its centre, surrounded by large 1970s and 80s estates at Neilstown, Quarryvale and Bawnogue, with newer development towards Liffey Valley.",
  cond="Big estates built to a common pattern, now all reaching the same point at the same time. Most of our Clondalkin work is full gutter, fascia and soffit replacement rather than piecemeal repair.",
  nb=["Lucan","Ballyfermot","Tallaght","Palmerstown","Neilstown","Quarryvale","Bawnogue","Rowlagh","Newlands"],
  revs=[("Whole road is at the same stage. We were the second house they did here.","Michael B.","Bawnogue"),
        ("Gutters, fascia and soffit together. Sensible and well priced.","Assumpta L.","Neilstown"),
        ("Turned up on time and did exactly what was quoted.","Derek H.","Clondalkin Village")]),
 dict(slug="lucan", name="Lucan", label="Co. Dublin", sub="West Dublin", exists=True,
  char="Lucan runs from the old village down by the Liffey out through huge modern estates at Adamstown, Esker and Griffeen, with 1980s housing in between.",
  cond="A lot of Lucan is newer than people think, and newer estates bring their own problems — tall houses, small gutters, rushed original fitting and downpipes undersized for the roof area they serve.",
  nb=["Clondalkin","Palmerstown","Leixlip","Adamstown","Esker","Griffeen","Ballyowen","Finnstown","Lucan Village"],
  revs=[("Three-storey house, gutters couldn't cope. Second downpipe fitted and problem solved.","Wayne S.","Adamstown"),
        ("Builder's fitting was poor from the start. Refitted the whole run properly.","Niamh G.","Griffeen"),
        ("Good communication and a tidy finish.","Robert D.","Esker")]),
 dict(slug="palmerstown", name="Palmerstown", label="Dublin 20", sub="West Dublin",
  char="Palmerstown is 1960s and 70s estate housing on the rising ground above the Liffey, with the older village and newer development near the Kennelsfort Road.",
  cond="The slope down to the Liffey and the mature planting through the older estates mean a lot of debris ends up in gutters. Housing of this age is also at the point where full replacement makes more sense than patching.",
  nb=["Lucan","Ballyfermot","Clondalkin","Chapelizod","Kennelsfort","Palmerstown Village","Woodfarm","Liffey Valley","Ballyowen"],
  revs=[("Estate is all the same age and all needing the same thing. Ours is done now.","Fintan M.","Woodfarm"),
        ("Cleared, repaired and advised honestly on what could wait.","Josephine R.","Kennelsfort"),
        ("Very reasonable and did a neat job.","Alan B.","Palmerstown")]),
 dict(slug="ballyfermot", name="Ballyfermot", label="Dublin 10", sub="West Dublin",
  char="Ballyfermot is a large 1950s corporation scheme — long uniform terraces along the main road and the estates behind it, with newer infill scattered through.",
  cond="Seventy-year-old housing with a great deal of original narrow guttering still in place. Undersized for today's rainfall, brittle with age, and identical from house to house, so the work tends to come in runs along a street.",
  nb=["Palmerstown","Inchicore","Clondalkin","Chapelizod","Cherry Orchard","Le Fanu","Kylemore","Drumfinn","Ballyfermot Road"],
  revs=[("Original gutters, never touched since the house was built. Long overdue and well sorted.","Bernard K.","Le Fanu"),
        ("Three of us on the road went in together. Good price.","Ann C.","Kylemore"),
        ("Quick, clean and no messing about.","Stephen O.","Ballyfermot")]),
 dict(slug="inchicore", name="Inchicore", label="Dublin 8", sub="South West Dublin",
  char="Inchicore is Victorian railway housing and artisan terraces around the works, with 1930s corporation schemes at Bulfin and Keogh Square and newer apartments closer to the canal.",
  cond="Some of the oldest continuously occupied housing in the city, much of it terraced with shared downpipes and parapet gutters. Original cast iron survives in plenty of places and needs judgement, not a blanket rip-out.",
  nb=["Ballyfermot","Drimnagh","Kilmainham","The Liberties","Bluebell","Bulfin","Goldenbridge","Emmet Road","Grand Canal"],
  revs=[("Old railway cottage, original cast iron. Repaired what was sound, replaced what wasn't.","Willie D.","Bulfin"),
        ("Shared downpipe with the neighbour, sorted for both of us.","Margaret T.","Goldenbridge"),
        ("Knew what they were looking at on an old house. That counts.","Peter H.","Inchicore")]),
 dict(slug="tallaght", name="Tallaght", label="Dublin 24", sub="South West Dublin", exists=True,
  char="Tallaght is one of Dublin's largest suburbs, from the older estates around Old Bawn and Jobstown to the newer builds out towards Citywest and Saggart.",
  cond="That range of housing means every gutter type imaginable. The open ground near the Dublin Mountains funnels wind and rain into Tallaght, which is hard on brackets, joints and downpipes.",
  nb=["Firhouse","Templeogue","Citywest","Saggart","Jobstown","Old Bawn","Greenhills","Kingswood","Bohernabreena"],
  revs=[("Gutters were overflowing onto the path every time it rained. Cleared and realigned in an afternoon.","Gary L.","Firhouse"),
        ("New gutters on a newer build out in Citywest. Tidy job, matched the colour perfectly.","Emma R.","Citywest"),
        ("Same day for a leak getting into the soffit. Sorted quickly.","Paul C.","Old Bawn")]),
 dict(slug="citywest", name="Citywest", label="Dublin 24", sub="South West Dublin",
  char="Citywest is almost entirely modern — 2000s estates, townhouses and apartments laid out around the business campus and the Luas line, with Saggart and Rathcoole alongside.",
  cond="Very exposed open ground on the edge of the city, and a lot of tall narrow houses with modest gutters. Wind loosens brackets and heavy rain overwhelms downpipes that were sized to the minimum.",
  nb=["Saggart","Tallaght","Rathcoole","Newcastle","Fortunestown","Citywest Village","Kingswood","Brownsbarn","Peamount"],
  revs=[("Very exposed out here. Heavier brackets made all the difference.","Andrea K.","Fortunestown"),
        ("Modern house, undersized downpipe. Added a second and it copes now.","Mark D.","Citywest Village"),
        ("Prompt and professional throughout.","Lisa M.","Brownsbarn")]),
 dict(slug="saggart", name="Saggart", label="Co. Dublin", sub="South West Dublin",
  char="Saggart keeps a small village core with substantial modern estate development around it, running out towards Rathcoole and the open country at the foot of the mountains.",
  cond="Right at the edge of the mountains and thoroughly exposed to weather coming off them. Wind-driven rain overshoots gutters on the exposed elevations, and brackets take a hammering through the winter.",
  nb=["Citywest","Rathcoole","Newcastle","Tallaght","Brittas","Fortunestown","Slade","Garters Lane","Aylmer"],
  revs=[("Rain was overshooting the gutter entirely on the windward side. They fitted a deeper profile.","Kenneth W.","Slade"),
        ("Storm loosened the front run. Refixed and braced properly.","Deirdre N.","Saggart Village"),
        ("Came out from the city with no extra charge for the trip.","Owen B.","Garters Lane")]),
 dict(slug="leixlip", name="Leixlip", label="Co. Kildare", sub="West Commuter Belt", exists=True,
  char="Leixlip has an old village core along the Liffey with large 1970s and 80s estates at Captain's Hill, Easton and Riverforest, plus newer development towards Confey.",
  cond="The Liffey valley planting drops a lot into gutters, and the estate housing from the seventies and eighties is now at the age where original systems are giving out across whole roads at once.",
  nb=["Lucan","Celbridge","Maynooth","Confey","Captain's Hill","Easton","Riverforest","Louisa Bridge","Collinstown"],
  revs=[("Liffey valley trees mean constant leaves. Regular clean has sorted us.","Brendan M.","Riverforest"),
        ("80s estate, original gutters gone. Full replacement, neatly done.","Carmel D.","Captain's Hill"),
        ("Good price and no travel charge from Dublin.","Ian F.","Confey")]),
 dict(slug="celbridge", name="Celbridge", label="Co. Kildare", sub="West Commuter Belt",
  char="Celbridge combines a fine old main street and period property near Castletown with very large modern estates built out through the 1990s and 2000s.",
  cond="Two extremes: period houses with cast iron and parapet gutters, and modern estates where the original fitting was rushed. Open Kildare countryside also means wind-driven rain on the exposed edges.",
  nb=["Leixlip","Maynooth","Lucan","Straffan","Castletown","Oldtown","Simmonstown","Ballyoulster","Hazelhatch"],
  revs=[("Modern estate, gutters never had the right fall. Refitted and the pooling stopped.","Sinead H.","Simmonstown"),
        ("Period house near Castletown, careful work on the old cast iron.","Owner","Celbridge"),
        ("Turned up when they said and did what they quoted.","Padraig L.","Ballyoulster")]),
 dict(slug="maynooth", name="Maynooth", label="Co. Kildare", sub="West Commuter Belt",
  char="Maynooth has the university and old town at its centre, ringed by large modern estates at Moyglare, Carton and Rail Park, plus a lot of student rental property.",
  cond="Rental and student property tends to go longer between inspections, so blockages here are often well advanced by the time we're called. The modern estates bring the usual fall and downpipe-sizing issues.",
  nb=["Celbridge","Leixlip","Kilcock","Dunboyne","Moyglare","Carton","Rail Park","Greenfield","Straffan"],
  revs=[("Rental property, gutters hadn't been touched in years. Cleared and repaired, now on a yearly check.","Landlord","Rail Park"),
        ("Modern estate house, downpipe couldn't cope. Second one fitted.","Cathal R.","Moyglare"),
        ("Good with tenants and easy to deal with.","Property Manager","Maynooth")]),
]
