# -*- coding: utf-8 -*-
# GENERATED FILE — DO NOT EDIT BY HAND.
#
# Rewritten wholesale by scripts/functions/publish-dublingutter-blog.mjs in the
# ai-os repo, which turns approved Core articles into dublingutter.ie blog
# posts. Hand-written posts live in blog.py's HAND_WRITTEN list and are never
# touched by that script; if a slug appears in both, the hand-written one wins.
#
# Same dict shape as HAND_WRITTEN:
#   slug, title, desc, cat, read, date, lede, body[(h2, html)], faq[(q, a)],
#   links[(href, label)]

POSTS = [
  dict(
    slug="gutter-repair-costs-in-dublin",
    title="Gutter Repair Costs in Dublin",
    desc="What a clear-and-reseal, a section swap and a full run actually cost — and how to tell which one your house needs",
    cat="Costs", read=10, date="2026-09-02",
    lede="Gutter repair in Dublin typically costs €120–€250 for a clear and reseal, €180–€400 for a bracket or section repair, €450–€900 for a full front or rear run replacement, and €1,600–€3,200 for a whole-house PVC replacement. Cast iron on period redbrick runs considerably higher. Prices are indicative — confirm after a survey.",
    body=[
      ("The short version",
       "<ul class=\"post-list\"><li>A clear and reseal on a standard 1930s Dublin semi runs <strong>€120–€250</strong>, and fixes overflow caused by moss, silt or a failed joint rather than the gutter itself.</li><li>A single bracket refix or a 1–2 metre section swap on PVC sits at <strong>€180–€400</strong>, most common on estate housing in Tallaght, Lucan and Clondalkin where UV has embrittled the plastic.</li><li>Replacing one full run — front or rear — of standard 112mm PVC on a semi is <strong>€450–€900</strong>, including new fascia brackets and outlets.</li><li>A whole-house PVC replacement on a three-bed semi is <strong>€1,600–€3,200</strong>; upgrading to 125mm deep-flow to cure undersizing adds roughly 15–20%.</li><li>Cast iron repair on Victorian and Edwardian redbrick in Rathmines, Phibsborough or Drumcondra is <strong>€150–€350 per metre</strong> to reinstate like-for-like, and needs specialist bracket and joint work.</li><li>Water spilling over the <em>front</em> edge — the outer lip — almost always means the gutter is either blocked, back-falling, or too small for the roof it serves; the fix depends on which.</li></ul>"),
      ("Why your gutter is overflowing at the front",
       "<p>Water pouring over the front edge of a gutter has three causes, and telling them apart before you spend anything is the whole game.</p>\n        <p><strong>Blockage or fall failure.</strong> Moss from a north-facing slope, sycamore seeds, roofing grit from a re-covered roof — any of it settles at the low end and dams the run. On Dublin's 1930s and '40s semis, the original PVC has usually been on the fascia for 30–40 years, and brackets sag under the weight of debris. Water backs up behind the block and tips over the front lip. Symptom: overflow only happens in heavy rain, and only at one point along the run.</p>\n        <p><strong>Joint or bracket failure.</strong> PVC gutter joints rely on an EPDM rubber seal that hardens after 20–25 years. A failed joint drips <em>behind</em> the gutter onto the fascia; a failed bracket lets the whole section drop, reversing the fall. Symptom: staining on the fascia board or soffit, or a visible dip when you sight along the run from below.</p>\n        <p><strong>Undersized profile.</strong> This is the one most Dublin homeowners miss. A lot of housing stock built between 1935 and 1970 was fitted with 112mm half-round PVC, which is fine for a small roof but genuinely undersized for a wide semi with a 45° pitch and 40m² of catchment on one side. In a proper Dublin downpour — the 30mm/hour bursts that show up several times a winter — the gutter physically cannot carry the volume, and water sheets over the front edge no matter how clean it is. Symptom: overflow along the <em>whole</em> run, only in heavy rain, on a gutter you've already had cleared.</p>\n        <p>Diagnosing which of the three you have decides whether you're spending €150 or €2,500. Any competent <a href=\"https://dublingutter.ie/\">Dublin gutter repair visit</a> should include sighting the fall with a level, checking joint seals from a ladder, and measuring the roof catchment against the gutter's rated flow.</p>"),
      ("How much does a gutter clear and reseal cost in Dublin?",
       "<p>A clear and reseal on a standard three-bed semi in Dublin is <strong>€120–€250</strong>, indicative, and takes 60–90 minutes for a two-person crew working from ladders. That covers hand-clearing both front and rear runs, flushing downpipes, checking outlets, and resealing one or two suspect joints with fresh EPDM gasket or a compatible sealant.</p>\n        <p>It is the right first step when:</p>\n        <ul class=\"post-list\"><li>The overflow is at one point, not along the whole run</li><li>The house has PVC gutter under 25 years old</li><li>You have not had it cleared in over two years</li><li>There are trees within 10 metres — every mature sycamore, lime or beech in a Dublin front garden puts measurable debris in the gutter</li></ul>\n        <p>It is the wrong first step when the fascia is stained (that's a joint or bracket problem), when the gutter visibly sags (bracket failure), or when overflow happens along the whole length in heavy rain (undersizing). Paying €200 to clear a gutter that's overflowing because it's 112mm on a roof that needs 125mm buys you exactly nothing.</p>"),
      ("Bracket refix and section repair — €180 to €400",
       "<p>A section repair replaces 1–3 metres of gutter or downpipe, or refits failed brackets, without disturbing the rest of the run. On PVC this is straightforward: cut out the failed length, fit new brackets at 800mm centres (the manufacturer spec — a lot of installers cheat to a metre, which is why they fail), and jointing to the existing profile with matching fittings.</p>\n        <p>The catch on older Dublin housing is profile matching. PVC guttering has gone through several generations — Marley, Osma, FloPlast, Brett Martin all use slightly different half-round and squareline profiles, and a 1985 gutter often will not accept a 2026 fitting. A good survey identifies the profile before the quote goes out; a bad one shows up on the day, discovers the mismatch, and either fits the wrong thing or writes a change order.</p>\n        <p>Section repair is the honest answer when:</p>\n        <ul class=\"post-list\"><li>One localised length has failed but the rest of the run has 10+ years left</li><li>The fascia and soffit behind it are sound (no rot, no staining beyond the immediate area)</li><li>The gutter profile is still commercially available</li></ul>"),
      ("When you need a full run replacement",
       "<p>A full run — the whole front or the whole rear of the house — replaced in 112mm half-round PVC on a standard semi is <strong>€450–€900</strong>, indicative, including new fascia brackets at proper centres, new outlets, new stop-ends and the joint work into the existing downpipe. It's a half-day job for two.</p>\n        <p>You're into full run territory when more than about a third of the length has failed, when brackets are pulling out of a soft fascia, or when the profile is obsolete and you can't get fittings. It's also the moment to decide whether to stay in 112mm or step up to 125mm deep-flow — see below.</p>\n        <p>Full run replacement is where the <a href=\"https://dublingutter.ie/\">full gutter replacement in Dublin</a> conversation usually starts, because once you're doing one side properly, doing the matching side within the same visit is roughly 30% cheaper than coming back for it later.</p>"),
      ("Whole-house PVC replacement — €1,600 to €3,200",
       "<p>A whole-house replacement on a three-bed semi — front and rear runs, all downpipes, all outlets, new fascia brackets throughout — is <strong>€1,600–€3,200</strong>, indicative. That range covers the honest variables:</p>\n        <ul class=\"post-list\"><li><strong>Access.</strong> Two-storey standard access is at the bottom of the range. Three-storey, restricted rear access, or anything requiring a cherry picker pushes toward the top.</li><li><strong>Fascia condition.</strong> If the fascia board is sound, brackets go straight on. If it's soft (very common on 1960s–'80s houses where the original softwood was never treated properly), fascia replacement is a separate job that must be done first or the new gutter fails within five years.</li><li><strong>Profile choice.</strong> 112mm half-round is the volume option. 125mm deep-flow — genuinely worth it on any semi with a large single-slope catchment — adds roughly 15–20% on materials and is the fix for undersized-profile overflow.</li><li><strong>Downpipe count and routing.</strong> Adding a second downpipe on a long run halves the flow each side has to carry and is often cheaper than upsizing the whole gutter.</li></ul>\n        <p>VAT at 13.5% applies on top of these ranges. Any <a href=\"https://dublingutter.ie/\">written gutter quote</a> should itemise brackets, gutter, downpipes, outlets and access separately so you can see what you're paying for.</p>"),
      ("Cast iron on Victorian and Edwardian redbrick",
       "<p>Cast iron is a different job and a different price. On the redbrick terraces of Rathmines, Ranelagh, Phibsborough, Drumcondra and the North Circular, the original half-round cast iron is often 100+ years old. Where it's still sound, it should be kept — replacing cast iron with PVC on a period property is both aesthetically wrong and, on a Protected Structure or in an ACA, often not permitted.</p>\n        <p>Cast iron repair runs <strong>€150–€350 per metre</strong>, indicative, depending on whether you're rehanging existing lengths on new brackets, splicing in reclaimed sections, or fitting new cast (which is available but expensive). The specialist work is:</p>\n        <ul class=\"post-list\"><li><strong>Bracket work.</strong> Original rise-and-fall brackets are often seized or corroded through. Reproduction brackets in galvanised or stainless are the standard replacement.</li><li><strong>Joint sealing.</strong> Traditional red-lead putty joints have been superseded by modern butyl or polyurethane sealants suited to cast iron movement.</li><li><strong>Paint system.</strong> A stripped and repainted cast iron gutter with a proper zinc-phosphate primer and two coats of gloss will last 15–20 years before it needs re-doing.</li></ul>\n        <p>Aluminium is a legitimate lookalike where full cast replacement isn't affordable — it holds paint well and weighs a fraction, but on a Protected Structure you'll need to check with the local authority conservation officer first. Most of South Dublin's period stock falls under <a href=\"https://dublindesignguide.dublincity.ie/\">Dublin City Council conservation guidance</a>.</p>"),
      ("How to tell which repair you actually need",
       "<p>Before you accept a quote, run this diagnostic yourself from the ground:</p>\n        <ol class=\"post-list\"><li><strong>Wait for rain, then look.</strong> Where is the water coming over — one point, or the whole run? One point is blockage or a low bracket. Whole run is undersizing.</li><li><strong>Sight along the gutter from below.</strong> It should fall gently toward the downpipe. A visible dip mid-run is a bracket problem, and no amount of resealing fixes it.</li><li><strong>Check the fascia.</strong> Vertical staining down the fascia board means water is escaping <em>behind</em> the gutter — a joint or bracket seal problem, not a capacity problem.</li><li><strong>Count downpipes.</strong> A semi with one downpipe serving a 40m² roof slope is undersized on downpipe count, not gutter size. A second downpipe is often the cheapest cure.</li><li><strong>Look at the moss.</strong> Heavy moss growth on the slates or tiles above means grit and organic matter are washing into the gutter continuously. Cleaning without addressing the roof buys you 12–18 months.</li></ol>\n        <p>A <a href=\"https://dublingutter.ie/\">proper gutter survey in Dublin</a> does all five of these and prices the repair against the honest cause, not the most expensive option.</p>"),
    ],
    faq=[
      ("How often should Dublin gutters be cleared?", "Once a year is enough for most Dublin houses without overhanging trees. With mature trees within 10 metres — very common on the older leafy roads in Rathgar, Terenure and Clontarf — twice a year, late autumn and late spring, is the sensible schedule."),
      ("Can I claim gutter repair on home insurance?", "Storm damage to gutters is usually covered under the storm peril, subject to your excess. Wear-and-tear, blockage and age-related failure are not. If a gutter has been pulled off in a named storm, take photographs immediately and get a written report before any repair work starts."),
      ("Is 125mm deep-flow guttering worth the extra?", "On a semi where the overflow is along the whole run in heavy rain, yes — it carries roughly 40% more water than 112mm half-round and is the correct fix for undersized-profile overflow. On a small terrace with a modest catchment, it's overspecified and not worth the 15–20% premium."),
      ("How long does PVC guttering actually last in Ireland?", "25–35 years for the gutter itself; the joint seals harden at 20–25 years and are usually the first thing to fail. Dublin's UV load is lower than the west coast, so PVC lasts toward the top of that range here."),
      ("Can gutter be replaced without scaffolding?", "Yes, in almost all cases. Standard two-storey semis are done from ladders or a cherry picker where reach demands it. Scaffolding only goes on very high buildings or busy-street jobs where public safety requires it, and it's itemised separately when it does."),
      ("Do I need to be home for the work?", "For external gutter work, no — access is from the outside and the crew works from ladders or a cherry picker. You'll need to be reachable by phone. Call (01) 265 8463 for a written quote, or use the site form for a same-week survey across Dublin."),
    ],
    links=[("/gutter-cleaning", "Gutter cleaning"), ("/gutter-repairs", "Gutter repairs"), ("/new-gutters", "New gutters")]),
]
