# -*- coding: utf-8 -*-
# GENERATED FILE — DO NOT EDIT BY HAND.
#
# Rewritten wholesale by scripts/functions/publish-dublingutter-blog.mjs in the
# ai-os repo, which turns approved Core articles into dublingutter.ie blog
# posts. Hand-written posts live in blog.py's HAND_WRITTEN list and are never
# touched by that script; if a slug appears in both, the hand-written one wins.
#
# Same dict shape as HAND_WRITTEN:
#   slug, title, desc, cat, read, date, lede, body[(h2, html)], faq[(q, a)],
#   links[(href, label)]

POSTS = [
  dict(
    slug="gutter-repair-costs-in-dublin",
    title="Gutter Repair Costs in Dublin",
    desc="Water spilling over the front? What each fix costs and how to tell which one you need",
    cat="Costs", read=11, date="2026-09-02",
    lede="Gutter repair costs in Dublin typically run from €95–€180 for a clear and reseal, €180–€350 for a bracket and section repair, €750–€1,400 for a full run replacement, and €2,500–€4,500 for a whole-house replacement in uPVC. The right figure depends on whether the fault is a blockage, a failed joint, or an undersized profile. Prices are indicative — a free survey confirms the actual number.",
    body=[
      ("The short version",
       "<ul class=\"post-list\"><li>A clear-and-reseal on a single joint sits at the bottom of the repair scale; a full elevation repair is priced as replacement work because that is effectively what it is.</li><li>uPVC installed on 1930s Dublin semis runs €50–€65 per metre supplied and fitted, aluminium €65–€75, cast iron €75–€90 — the profile chosen matters more than the length.</li><li>Water spilling over the front edge on a 1970s Tallaght or Clondalkin estate is usually an undersized 112mm half-round, and no repair fixes it — upsizing to 125mm deep-flow does.</li><li>A standard three-bed semi carries roughly 15–20 metres of guttering front and rear combined, so multiply the per-metre rate to sanity-check any whole-house quote.</li><li>Cast iron on Rathmines or Phibsborough redbrick is usually worth repairing in matching sections rather than ripped off wholesale — surface rust is repairable, rust through the base of the section is not.</li><li>Every full replacement carries a Lifetime Leak Guarantee alongside the 10-year written workmanship guarantee; repairs carry the 10-year cover only.</li></ul>"),
      ("Why is water spilling over the front edge?",
       "<p>Three faults produce the same symptom, and telling them apart is the whole job before any money is spent.</p>\n        <p><strong>A blockage or a lost fall</strong> dams the run at one point. Leaves, moss shed off the slates, and silt build gradually against an outlet or at a low spot where a bracket has dropped. Water backs up behind the dam and takes the shortest route out — over the front lip. You will usually see it in one place on the run, not along the whole length. This is a cleaning job, sometimes with a bracket reset behind it.</p>\n        <p><strong>A failed joint or bracket</strong> drips behind the gutter, not over the front. If the fascia below is stained or the wall behind the downpipe is wet, the water is escaping at the back of the profile rather than the front. Joint seals harden with UV exposure — Dublin's older uPVC, fitted in the 1980s and 1990s across Cabra, Crumlin and Terenure, is often past the point where a reseal will hold, and the union needs replacing.</p>\n        <p><strong>An undersized profile</strong> overflows along the whole run even when the gutter is spotless. Many 1970s estates — Tallaght, Clondalkin, Coolock, Ballymun — were fitted with 112mm half-round that never had the capacity for the roof pitched above it. In a heavy Dublin shower, the water sheet coming off the slates simply exceeds what the profile can carry, and it sheets over the front for the length of the elevation. No repair solves it; the fix is a larger profile.</p>\n        <p>The reason for going up and looking rather than pricing from the ground is that these three faults produce identical spillover but have prices an order of magnitude apart.</p>"),
      ("How much does a gutter repair cost in Dublin?",
       "<p>Repairs run from a single joint to a whole elevation, so a single range is useless. The bands below reflect what the same crew, insurance and 10-year written guarantee cost for different scopes of work.</p>\n        <div style=\"overflow-x:auto\"><table><thead><tr><th>Scope of repair</th><th>Indicative price</th><th>What it covers</th></tr></thead><tbody><tr><td>Clear, flush and reseal one joint</td><td>€95 – €180</td><td>Clearing the run and downpipes, flushing to confirm flow, sealing or replacing one union</td></tr><tr><td>Bracket and short section repair</td><td>€180 – €350</td><td>Two or three brackets, one damaged section swapped, fall reset on part of the run</td></tr><tr><td>Half-day repair on one elevation</td><td>€350 – €650</td><td>Several brackets, multiple joints, a section swap and outlet renewal on one side</td></tr><tr><td>Full elevation repair</td><td>€750 – €1,400</td><td>Priced as replacement work because that is effectively what it is</td></tr><tr><td>Whole-house uPVC replacement</td><td>€2,500 – €4,500</td><td>New gutters, brackets, unions, outlets and downpipes to the full house</td></tr><tr><td>Whole-house aluminium replacement</td><td>€3,200 – €5,500</td><td>As above in aluminium profile — longer lifespan, tighter joints</td></tr><tr><td>Cast iron section repair on period house</td><td>€400 – €900 per section</td><td>Matching heritage profile, splice in and reseal; retains the original character</td></tr></tbody></table></div>\n        <p>Prices are indicative and confirmed free after a site survey. There is no call-out fee and small work is real work — a single joint reseal is billed as a single joint reseal, not padded out.</p>\n        <p>What moves the number every time: the length of the run, the material, the height and access, whether the fascia behind the gutter is sound, and whether the downpipes and outlets are being renewed at the same time.</p>"),
      ("When does a repair stop making sense?",
       "<p>A cracked joint, a sagging bracket, a short damaged section — these are repairs. Money spent on them buys another twenty years of the gutter you have.</p>\n        <p>A run that sags between every bracket, cracks along its length, or has more patches than gutter has stopped being economical to repair. On brittle 1980s uPVC — common across Cabra, Crumlin and the older parts of Terenure and Clontarf — the material itself has lost the flex to hold a new bracket without splitting. Refixing to a full elevation on that gutter costs most of what a new elevation costs, and it carries repair-scope cover rather than the Lifetime Leak Guarantee that comes with a full replacement.</p>\n        <p>The honest rule: if the repair quote is more than 60% of the replacement quote for the same elevation, replace it. You get a longer-lived gutter, tighter joints, and the leak guarantee that only comes with new work.</p>"),
      ("What about the fascia behind the gutter?",
       "<p>Where the board a gutter is screwed to has gone soft — a common finding on 1930s and 1940s semis where the original timber fascia was never capped — there is nothing for a new bracket to bite into. Fitting new gutter to failed board is a wasted visit.</p>\n        <p>In that case gutter, fascia and soffit get done together in one visit. The gutter has to come off to reach the board anyway, so doing both at once is considerably cheaper than doing them in two separate visits six months apart. Expect roughly €85–€120 per metre for the combined roofline replacement on uPVC, all in, and confirm on survey — the driver is whether the rafter feet underneath are sound or need attention as well.</p>"),
      ("What does whole-house replacement cost by material?",
       "<p>Per metre, supplied and installed, including brackets, unions and outlets:</p>\n        <div style=\"overflow-x:auto\"><table><thead><tr><th>Material</th><th>Per metre installed</th><th>Typical whole-house (15–20m)</th></tr></thead><tbody><tr><td>uPVC</td><td>€50 – €65</td><td>€2,500 – €4,500</td></tr><tr><td>Aluminium</td><td>€65 – €75</td><td>€3,200 – €5,500</td></tr><tr><td>Cast iron (heritage)</td><td>€75 – €90</td><td>Quoted per house — usually done in matching sections</td></tr></tbody></table></div>\n        <p>uPVC is the standard fit on most Dublin semis and terraced houses and, well fitted, gives thirty years or more. Aluminium is worth the premium on exposed coastal gables — Howth, Sutton, Malahide, Sandymount, Dun Laoghaire — where wind loading pulls uPVC away from the fascia faster than inland runs.</p>\n        <p>Cast iron on Georgian and Victorian redbrick — Rathmines, Phibsborough, Drumcondra, Portobello, Ranelagh — is a different conversation. The original material is usually worth saving. Surface rust that has pitted the outside is repairable; rust through the base of the section is not. We repair in matching profile rather than ripping off period character wholesale.</p>"),
      ("How do I tell if my Dublin gutter needs replacement rather than repair?",
       "<p>Six signs the run is past economical repair, drawn from Dublin housing stock we see every week:</p>\n        <ol class=\"post-list\"><li><strong>Sags visible between every bracket</strong> — the profile has lost its structural memory, common on 40-year-old uPVC.</li><li><strong>Overflow along the entire front run in heavy rain, gutter clean</strong> — an undersized profile, typical on 1970s 112mm half-round.</li><li><strong>Cracks running along the length of a section</strong> rather than at joints — UV embrittlement, no seal will hold.</li><li><strong>More than three separate patches on one elevation</strong> — the run is telling you it is finished.</li><li><strong>Fascia stained or rotted behind the gutter along its length</strong> — water has been tracking behind for years.</li><li><strong>Brackets pulling through the fascia in more than two places</strong> — the substrate has failed, not just the fittings.</li></ol>\n        <p>One of these on its own is usually a repair. Three or more together is replacement territory.</p>"),
      ("What's included in the price, and what isn't?",
       "<p>Every quote from us includes a written breakdown before anything starts, the 10-year workmanship guarantee handed over in writing before the contract is signed, and — on full replacements — the Lifetime Leak Guarantee. The run is flushed and tested with water before we leave, so you see it clear rather than being told it does.</p>\n        <p>What isn't in a gutter price: internal repairs to ceilings or walls stained by a long-running leak, or works to the roof covering itself. Slates, tiles and flat-roof work sit with our sister brand, <a href=\"https://recommendedroofing.ie\">Recommended Roofing</a>. If a survey turns up a covering issue that's driving water into the gutter rather than a gutter fault, we say so plainly.</p>\n        <p>For related guttering work, see our pages on <a href=\"https://dublingutter.ie/\">gutter cleaning across Dublin</a>, <a href=\"https://dublingutter.ie/\">full gutter replacement</a>, <a href=\"https://dublingutter.ie/\">fascia and soffit repairs</a>, and <a href=\"https://dublingutter.ie/\">downpipe repair and replacement</a>. Homeowners in North County Dublin can find area-specific detail on our <a href=\"https://dublingutter.ie/\">North Dublin service pages</a>, and equivalents cover the <a href=\"https://dublingutter.ie/\">South Dublin area</a>.</p>"),
      ("Storm damage and insurance",
       "<p>Storm damage to guttering is usually covered under the storm peril of a standard Irish home insurance policy, subject to the excess. Wear and tear, blockage and age-related failure are not. If a gutter has come away in a named storm — Éowyn, Ashley or any subsequent — photograph it immediately from the ground and from an upstairs window, and get a written report before any repair starts. We produce that report as part of the survey at no extra charge.</p>"),
    ],
    faq=[
      ("Do you charge a call-out fee to quote a gutter repair in Dublin?", "No. Surveys and written quotes are free across Dublin city and county. We go up and look rather than pricing from the ground, because the difference between a €120 joint reseal and a €3,500 undersized-profile replacement is not visible from the driveway."),
      ("Can you match my existing cast iron gutter on a period house?", "In almost every case, yes. We repair Georgian and Victorian cast iron in matching profile — retaining the original character rather than replacing the lot in uPVC. Splice-in section repairs on redbrick terraces in Rathmines, Phibsborough and Drumcondra are routine work."),
      ("How long does a gutter repair take?", "A single joint or bracket is usually a short visit — a couple of hours including flushing the run. A section swap or fall reset on one elevation is a half-day. A full elevation repair or replacement runs one to two days on a standard three-bed semi."),
      ("Is the gutter repair guaranteed?", "Yes. Every repair carries our 10-year written workmanship guarantee, handed over in writing before contracts are signed. Full replacements additionally carry our Lifetime Leak Guarantee. The distinction matters — repairs carry the workmanship cover only, because the surrounding gutter is not new work."),
      ("Do I need gutter guards after a repair?", "Usually not. On most Dublin houses a clear on a schedule is cheaper and works better than guards, which keep leaves out but trap silt and moss and still need cleaning. Guards earn their place under heavy overhanging trees where ladder access is genuinely difficult — parts of Castleknock, Mount Merrion and Rathgar being the honest examples."),
      ("What if my gutter is overflowing right now in heavy rain?", "Call (01) 265 8463. An overflowing gutter tracking water into a wall or ceiling is not a scheduled job — we prioritise same-day where the diary allows. Say it is an emergency on the phone rather than booking a standard survey three days out. --- Call (01) 265 8463 or use the contact form for a free survey and a written quote across Dublin city and county. Mon–Sat 08:00–18:00."),
    ],
    links=[("/gutter-cleaning", "Gutter cleaning"), ("/gutter-repairs", "Gutter repairs"), ("/new-gutters", "New gutters")]),
]
