# -*- coding: utf-8 -*-
# GENERATED FILE — DO NOT EDIT BY HAND.
#
# Rewritten wholesale by scripts/functions/publish-dublingutter-blog.mjs in the
# ai-os repo, which turns approved Core articles into dublingutter.ie blog
# posts. Hand-written posts live in blog.py's HAND_WRITTEN list and are never
# touched by that script; if a slug appears in both, the hand-written one wins.
#
# Same dict shape as HAND_WRITTEN:
#   slug, title, desc, cat, read, date, lede, body[(h2, html)], faq[(q, a)],
#   links[(href, label)]

POSTS = [
  dict(
    slug="gutter-repair-costs-in-dublin",
    title="Gutter Repair Costs in Dublin",
    desc="What overflowing at the front actually costs to fix, and how to tell a €150 clean from a €1,500 realignment",
    cat="Costs", read=10, date="2026-09-02",
    lede="Gutter repair in Dublin starts at around €500 for a couple of leaking joints on one run, with most jobs landing between €1,000 and €1,900 for a sagging run realigned, brackets renewed and joints resealed. A single-run clear and reseal is cheaper; a full-house replacement on a semi runs €1,000–€1,400 in uPVC.",
    body=[
      ("The short version",
       "<ul class=\"post-list\"><li><strong>Clean and flush only:</strong> priced per job after a look at the house, with downpipes included — the honest answer on a Cabra semi is different from a three-storey Ranelagh redbrick.</li><li><strong>Small repair (one run, a couple of leaking joints):</strong> €500–€800, done in a single visit.</li><li><strong>Typical repair (sagging run realigned, brackets renewed, joints resealed, a downpipe sorted):</strong> €1,000–€1,900.</li><li><strong>Extensive or cast iron repair on a period property:</strong> €1,900–€3,000, because welding and matching sections take time.</li><li><strong>Full replacement on a standard ~20-metre semi:</strong> €1,000–€1,400 in uPVC, €1,300–€1,800 in aluminium, €2,100–€2,800 in cast iron — includes strip-out, new brackets, unions and downpipes.</li><li><strong>1970s estates in Tallaght, Clondalkin and Coolock</strong> commonly need upsizing to a 125mm deep-flow profile because the original 112mm half-round is undersized for the roof it serves.</li></ul>"),
      ("Why is water spilling over the front of my gutter?",
       "<p>Water tipping over the front edge in heavy rain has three causes, and they need telling apart before any money is spent. The wrong diagnosis is the reason people pay twice.</p>\n        <p><strong>A blockage or a lost fall</strong> dams the run at one point. Leaves, moss and roof grit collect at the low end near the outlet, or a bracket has dropped and created a new low point mid-run. Water backs up behind the dam and spills over the front lip. This is a cleaning and re-fall job, not a replacement.</p>\n        <p><strong>A failed joint or bracket</strong> lets water drip behind the gutter onto the fascia rather than out the front. If the front of the house shows staining down the render below the gutter line, and the fascia board above is soft or blackened, this is the culprit. Sealing the union, replacing a cracked bracket, or renewing a short section of gutter fixes it.</p>\n        <p><strong>An undersized profile</strong> is the Dublin classic that gets missed. On many 1930s semis and 1970s estates the original 112mm half-round PVC is simply too small for the roof area draining into it. Overflow happens every heavy downpour, even the day after it has been cleaned, because there is nowhere for the water to go. The fix is upsizing to a 125mm deep-flow profile, and no amount of cleaning or resealing will change the outcome.</p>\n        <p>The reason a survey matters here is that the difference between the three is not visible from a driveway. A gutter can look fine from below and be running backwards from a dropped bracket ten metres in; a clean run can be undersized by design.</p>"),
      ("How much does a gutter clean cost in Dublin?",
       "<p>Cleaning is priced per job after a look at the property rather than per metre, because size of house, roof height, ladder access and how much material is up there all move it more than the length of gutter does. Downpipes are included as standard — <a href=\"https://dublingutter.ie/gutter-cleaning\">clearing a gutter and leaving a blocked downpipe</a> achieves nothing, and it is one of the more common ways a first-time customer has been shortchanged elsewhere.</p>\n        <p>Most Dublin houses need one clear a year, in late autumn once the leaves are down. A second clear in spring earns its money on the leafier roads — Rathgar, Terenure, Clontarf, Mount Merrion, Castleknock — and on any north-facing roof that holds moss. Estates on open ground in Citywest, Clonsilla or Adamstown usually manage on the annual.</p>\n        <p>There is no call-out fee, and the quote is written before anything starts.</p>"),
      ("What does a bracket and section repair cost?",
       "<p>This is the middle band and where most Dublin repair jobs actually land. <strong>Typical repair work runs €1,000–€1,900</strong> and covers realigning a sagging run, renewing the brackets that have pulled through or dropped, replacing joint seals and unions that have hardened past resealing, and sorting a downpipe if one has come loose or split.</p>\n        <p>What moves the number inside that band:</p>\n        <ul class=\"post-list\"><li><strong>How much of the system is being worked on.</strong> A single elevation is at the bottom; front and rear together push toward the top.</li><li><strong>The material.</strong> uPVC works are quicker than aluminium; both are considerably faster than cast iron.</li><li><strong>Height and access.</strong> A two-storey semi with driveway access is straightforward. A three-storey Georgian on Portobello with cars parked tight to the kerb needs a tower rather than a ladder, and the day costs more.</li><li><strong>Whether the fascia is sound.</strong> If the board a bracket is screwed to has rotted, there is nothing for a new bracket to bite into. Fascia and soffit then have to come off in the same visit, which is more work but <a href=\"https://dublingutter.ie/fascia-soffit\">considerably cheaper than doing it twice</a>.</li></ul>\n        <p>Small jobs — a couple of leaking joints on one run, no realignment, no brackets — sit at €500–€800. This is the honest answer for a single failed union on a modern semi in Adamstown, and quoting it as a €1,500 job would be dishonest.</p>\n        <p>Cast iron on a period redbrick is a different animal. Rust that has pitted the surface is repairable, often by welding and repainting rather than replacement. Rust through the base of the section is not. <strong>Extensive or cast iron repair work runs €1,900–€3,000</strong>, and the extra reflects welding time, matching sections and the care period ironwork asks for.</p>\n        <p>Every repair carries the <a href=\"https://dublingutter.ie/guarantee\">10-year written workmanship guarantee</a>. The Lifetime Leak Guarantee applies to full replacements only — it is worth being clear about which one covers your job before signing.</p>"),
      ("When is it cheaper to replace the whole run?",
       "<p>A run that sags between every bracket, cracks along its length, or has been patched more times than it has been left alone has stopped being economical to repair. The rough test is that once a repair quote crosses about 60% of the replacement figure, you are paying twice for something that will need doing properly inside five years.</p>\n        <p>Full replacement on a standard three-bed Dublin semi carries roughly 15–20 metres of gutter across front and rear combined. Indicative installed prices, including strip-out and disposal, new brackets, unions, outlets and downpipes:</p>\n        <div style=\"overflow-x:auto\"><table><thead><tr><th>Material</th><th>Typical semi (~20 m)</th><th>Larger or detached (~50 m)</th></tr></thead><tbody><tr><td>uPVC</td><td>€1,000 – €1,400</td><td>€2,900 – €3,600</td></tr><tr><td>Aluminium</td><td>€1,300 – €1,800</td><td>€3,600 – €4,500</td></tr><tr><td>Cast iron (heritage)</td><td>€2,100 – €2,800</td><td>€5,500 – €6,500</td></tr></tbody></table></div>\n        <p>These are indicative figures. Exact rates are confirmed free after a site survey.</p>\n        <p>Material is the biggest lever. Materials alone run about €10 per metre for uPVC up to €50 per metre for cast iron, and on a 50-metre detached house that difference moves the job by roughly €3,000. Every <a href=\"https://dublingutter.ie/gutter-replacement\">full gutter replacement</a> carries the Lifetime Leak Guarantee alongside the 10-year written guarantee.</p>"),
      ("Dublin's housing stock and what usually fails",
       "<p>The address is a fair predictor of the fault:</p>\n        <ul class=\"post-list\"><li><strong>Georgian and Victorian redbrick</strong> in Rathmines, Phibsborough, Drumcondra, Portobello and Ranelagh runs on original cast iron, often worth saving. Repair beats replacement here almost every time, and the pricing sits in the extensive band because welding and matching sections are involved.</li><li><strong>1930s and 1940s semis</strong> in Cabra, Crumlin, Terenure and Clontarf were fitted with uPVC decades ago that is now brittle from UV, with joint seals hardened past the point of resealing. A couple of unions will fail, then another two the following winter, and at some point full replacement of an elevation is cheaper than the rolling repairs.</li><li><strong>1970s estates</strong> in Tallaght, Clondalkin, Coolock and Ballymun carry standard 112mm half-round profile that is frequently undersized for the roof area. Cleaning does nothing here; upsizing to 125mm deep-flow is the actual fix.</li><li><strong>Newer developments</strong> in Citywest, Clonsilla and Adamstown are generally sound — most calls are blockages and the occasional bracket.</li></ul>\n        <p>Coastal exposure changes the maths on the northside and along the bay. Howth, Sutton, Malahide, Sandymount and Dun Laoghaire take wind loading that inland areas do not, and bracket spacing needs closing up. A run that has held fine in Tallaght for twenty years will pull away from an exposed gable in Sutton in ten.</p>"),
      ("Is the damage a claim on my home insurance?",
       "<p>Storm damage to guttering is usually covered under the storm peril, subject to your excess. Wear and tear, blockage and age-related failure are not, and this is where most claims get declined. If a gutter has come away in a named storm, photograph it immediately from the ground, keep any pieces, and get a written report before any repair starts. A repair invoice dated three weeks after Storm Éowyn with no supporting photos is a hard sell to a loss adjuster.</p>"),
      ("How the job actually runs",
       "<ol class=\"post-list\"><li>You call <strong>(01) 265 8463</strong> or send the form (Mon–Sat 08:00–18:00). Overflowing water tracking into a wall or ceiling is not a scheduled job — say so on the phone and it gets prioritised, same-day where the diary allows.</li><li>A <a href=\"https://dublingutter.ie/contact\">free survey with no call-out fee</a> — we go up and inspect rather than pricing from the ground.</li><li>A written quote with a breakdown of the work and the guarantee terms, before anything is signed.</li><li>The work, done by directly employed crews — <a href=\"https://dublingutter.ie/about\">no subcontractors</a>. Most repairs are a single visit; a full semi replacement is one to two days.</li><li>The run is flushed and tested with water before we leave.</li><li>Guarantee handed over in writing — 10 years on the workmanship, Lifetime Leak on a full replacement.</li></ol>"),
    ],
    faq=[
      ("Do you charge a call-out fee for a quote?", "No. Surveys and written quotes are free across Dublin city and county, and we go up on the roofline to inspect rather than pricing from the ground."),
      ("How do I know if my gutter is undersized rather than blocked?", "If the run overflows in heavy rain within days of a clean, and the overflow is spread along most of the length rather than at one point, the profile is almost certainly too small for the roof draining into it. Typical on 1970s estates with the original 112mm half-round."),
      ("Can cast iron gutters be repaired or do they always need replacing?", "Cast iron on a Dublin period house is usually worth repairing in matching sections rather than replacing the lot. Pitted rust on the surface is repairable by welding and repainting. Rust through the base of the section is not, and that section has to be swapped."),
      ("How long should new gutters last?", "Well-fitted uPVC should give thirty years or more. Aluminium and cast iron considerably longer, particularly on inland properties out of heavy coastal exposure."),
      ("Do you offer any guarantee on repair work?", "Yes — every repair carries a 10-year written workmanship guarantee. The Lifetime Leak Guarantee applies to full gutter or roofline replacements only, not to repairs or partial work."),
      ("What if the fascia behind the gutter has rotted?", "The gutter has to come off to reach the board, so fascia and soffit are done in the same visit as the guttering. It is more work, but considerably cheaper than doing it twice. Call (01) 265 8463 for a free survey across Dublin city and county — Mon–Sat 08:00–18:00."),
    ],
    links=[("/gutter-cleaning", "Gutter cleaning"), ("/gutter-repairs", "Gutter repairs"), ("/new-gutters", "New gutters")]),
  dict(
    slug="fascia-and-soffit-replacement-in-dublin",
    title="Fascia and Soffit Replacement in Dublin",
    desc="Red-brick terraces, rot behind the gutter, and what to specify on a Victorian roofline",
    cat="Costs", read=10, date="2026-09-15",
    lede="Fascia and soffit replacement on a Dublin red-brick terrace runs from around €50 per metre for uPVC through to aluminium capping over sound timber, and is almost always done with the guttering because the gutter has to come off to reach the board. Rot behind the gutter is the usual trigger, and specification decides whether it comes back.",
    body=[
      ("The short version",
       "<ul class=\"post-list\"><li>Fascia and soffit are priced with the guttering when done together, because the gutter has to be removed to reach the board — one visit is considerably cheaper than two.</li><li>On Phibsborough, Drumcondra and Portobello terraces the fascia sits behind a cast iron gutter, and the rot is almost always at the wall junction where the eaves close against the brick.</li><li>uPVC replacement board and soffit is the standard specification; aluminium capping over sound timber is a repair strategy, not a like-for-like replacement.</li><li>Soffit ventilation on a 1900s terrace is usually absent — a continuous 10mm vent strip or 25,000mm²/m equivalent should be specified when the soffit is renewed.</li><li>Every full replacement carries our 10-year written workmanship guarantee, and the roofline replacement also carries the Lifetime Leak Guarantee.</li><li>Indicative full uPVC gutter replacement on a typical Dublin semi runs €1,000–€1,400; fascia and soffit is quoted alongside after a free survey.</li></ul>"),
      ("Why rot appears behind the gutter on Dublin terraces",
       "<p>The Victorian and Edwardian red-brick terraces that line <strong>Phibsborough, Drumcondra, Portobello, Ranelagh and Rathmines</strong> were built between roughly 1880 and 1915, and the roofline detail has barely changed in the intervening 120 years. A softwood fascia board is nailed to the rafter feet. A softwood soffit closes the eaves back to the brickwork. And a cast iron gutter — ogee or half-round — is bolted through the fascia into the rafter end.</p>\n        <p>That detail worked for a century because the cast iron was maintained. Once the gutter starts to weep at a joint, or the fall goes off, water runs down the back of the gutter rather than through it. The fascia is the first thing it hits. Softwood behind a leaking cast iron gutter in a Dublin winter — 750–850mm of annual rainfall, weeks on end without drying — will go in five or six years.</p>\n        <p>The rot then travels. Because the fascia meets the soffit at a right angle, water tracks along the top edge of the soffit and out to the wall junction, where the eaves close against the red brick. <strong>The wall junction is where you see it first from the ground</strong> — a stain on the brick, moss on the soffit corner, sometimes a soffit board that has dropped away entirely and left the rafter tail visible.</p>\n        <p>If you can see the rafter tail from the footpath, the fascia behind it has almost certainly gone, and the gutter fixing is holding on to soft timber.</p>"),
      ("How to tell fascia rot from a gutter leak",
       "<p>From the ground, the two look identical — water where it should not be. From a ladder they are obvious, and they need telling apart before money is spent. Our <a href=\"https://dublingutter.ie/\">gutter repair service in Dublin</a> starts with a look rather than a price from the driveway, because the difference decides whether the job is €800 or €4,000.</p>\n        <ul class=\"post-list\"><li><strong>Gutter leak, board sound</strong> — the fascia paint is intact, the board rings solid when tapped, the leak is at a joint or a bracket. A repair.</li><li><strong>Board soft, gutter still holding</strong> — the paint bubbles, a screwdriver goes into the board without resistance, but the gutter is not yet sagging. Fascia replacement now, before the brackets pull through.</li><li><strong>Board gone, gutter sagging</strong> — the run has dropped between brackets, the fascia is black at the top edge, the soffit is stained at the wall. Full roofline replacement on that elevation.</li></ul>\n        <p>The third case is what we most often see on terraces where the last cast iron repaint was in the 1990s. The gutter is no longer bolted to timber — it is bolted to compost. New brackets will not bite, which is why patching one elevation with a fresh run of uPVC on a rotted fascia fails inside two winters.</p>"),
      ("uPVC or aluminium capping — what to specify",
       "<p>Two legitimate specifications exist for a Dublin terrace, and they solve different problems.</p>\n        <p><strong>Full uPVC replacement.</strong> The rotted fascia and soffit are stripped back to the rafter feet. New tanalised timber is fitted where the rafter tails themselves are soft (which happens on north-facing rear elevations more often than owners expect). A 16mm or 18mm uPVC replacement fascia board is fixed through to sound timber, and a hollow or vented soffit is fitted underneath. This is the standard specification and what most Dublin houses end up with.</p>\n        <p><strong>Aluminium capping over sound timber.</strong> A pre-formed aluminium cover is fitted over the existing fascia, which stays in place. This is a valid approach only where the underlying timber is genuinely sound and the owner wants to preserve the original board profile — most often on protected structures or in conservation areas where a heavier uPVC section would look wrong. Capping rotted timber is a way to hide a problem, not fix one, and we will say so.</p>\n        <p>On the terraces of Portobello and Ranelagh, where the eaves detail is visible from the street and the neighbouring houses have kept a slim painted fascia, aluminium capping is worth the conversation. On a 1930s semi in Cabra or Crumlin, uPVC replacement is almost always the right call.</p>\n        <p>We do not specify a slim square-edged uPVC board on a Victorian terrace where the original was an ogee profile with a moulded lower edge. The profile matters — the roofline reads from thirty metres away, and a flat board on a period house looks wrong for as long as it is up there.</p>"),
      ("The ventilation gap that was never there",
       "<p>Here is the specification detail that gets missed on almost every fascia and soffit replacement in Dublin, and matters more now than it did when the house was built.</p>\n        <p>Victorian and Edwardian terraces were built without soffit ventilation. The roof space breathed through gaps in the slating and around the ridge — leaky by modern standards, but it worked. Once a house has been re-slated, re-felted with a modern breather membrane, and had loft insulation upgraded to the current 300mm depth to qualify for a <strong><a href=\"https://www.seai.ie/grants/home-energy-grants/\">SEAI Better Energy Home grant</a></strong>, that airflow disappears.</p>\n        <p>The result is condensation on the underside of the roof felt in winter, which drips onto the top of the insulation, keeps the rafter feet damp, and rots the fascia from behind as well as in front.</p>\n        <p>When we renew a soffit we specify continuous ventilation — either a 10mm continuous vent strip along the back edge of the soffit, or circular soffit vents at 300mm centres, delivering the equivalent of 25,000mm² of free airflow per linear metre. On a house that has been re-insulated in the last ten years this is not optional. Renewing the soffit without the vent strip is renewing the problem.</p>"),
      ("What the job actually involves",
       "<p>A fascia, soffit and gutter replacement on one elevation of a Dublin terrace runs to a predictable sequence. The <a href=\"https://dublingutter.ie/\">full roofline replacement process</a> is:</p>\n        <ol class=\"post-list\"><li>Scaffold or tower access set up, usually a single day for a front elevation off the street.</li><li>Cast iron gutter carefully lifted off — bagged for scrap value where the customer wants to keep it, or removed by us.</li><li>Rotted fascia and soffit stripped back to sound timber. Rafter feet inspected and replaced or sistered where necessary.</li><li>Felt eaves detail checked and, on older re-roofs, an eaves protector tray fitted to carry water off the felt and into the new gutter.</li><li>New uPVC fascia fixed to sound timber. Vented soffit fitted underneath. Trims closed at the wall junction with a proper stop end, not silicone.</li><li>New gutter run set to a fall of roughly 1:600 (about 5mm over 3 metres), on brackets at maximum 800mm centres — closer on coastal elevations in Clontarf, Sandymount and Sutton where wind loading matters.</li><li>Downpipes reconnected to the existing hoppers or renewed, and the run water-tested before we leave.</li></ol>\n        <p>For a typical mid-terrace front elevation of 8–10 metres, this is a one to two day job with two crew. A full front-and-rear on a semi runs two to three days. Every full replacement carries the <a href=\"https://dublingutter.ie/\">10-year written workmanship guarantee and the Lifetime Leak Guarantee</a>, handed over in writing before contracts are signed.</p>"),
      ("Indicative costs",
       "<p>Prices below are indicative and confirmed free after a site survey. Fascia and soffit is priced with the guttering because the two are done together — the gutter has to come off to reach the board, and separating the invoices does not separate the labour.</p>\n        <div style=\"overflow-x:auto\"><table><thead><tr><th>Element</th><th>Indicative cost</th></tr></thead><tbody><tr><td>uPVC gutter, typical Dublin semi (~20m front + rear)</td><td>€1,000 – €1,400</td></tr><tr><td>Aluminium gutter, same house</td><td>€1,300 – €1,800</td></tr><tr><td>Cast iron replacement (heritage / conservation)</td><td>€2,100 – €2,800</td></tr><tr><td>Fascia and soffit renewal</td><td>Quoted with the guttering after survey</td></tr></tbody></table></div>\n        <p>Material is the single biggest lever on the guttering side. Fascia and soffit costs are driven by the length of run, the height, whether the rafter feet are sound, and whether scaffold or a tower is needed for access. There is no call-out fee, and a written breakdown is handed over before anything is signed.</p>"),
    ],
    faq=[
      ("Can I replace the fascia without touching the gutter?", "Not on a house where the gutter is bolted through the fascia, which covers every Dublin terrace and semi we work on. The gutter has to come off to fit the new board. Doing them in one visit is considerably cheaper than paying for access twice."),
      ("Is uPVC fascia appropriate on a protected structure in Dublin?", "Not always. Protected structures and buildings in an Architectural Conservation Area (ACA) may require timber replacement in a matching profile, or aluminium capping over sound original timber. Check with Dublin City Council's conservation section before specifying — this is one of the few cases where \"like for like in timber\" is the honest answer."),
      ("How long does uPVC fascia last on an exposed Dublin elevation?", "Well-fitted uPVC on a properly ventilated soffit should give thirty years or more. The failure mode is almost never the plastic itself — it is the timber behind it going soft because the soffit was not ventilated when the roof was upgraded."),
      ("Do you match the ogee profile of the original cast iron?", "Yes, in the common profiles and colours — black is the standard for red-brick terraces. Where the original ogee section matters (Portobello, Ranelagh, parts of Rathmines) we specify a matching uPVC or aluminium profile rather than a modern square-edged board that would read wrong on the elevation."),
      ("What about the party wall between two terraced houses?", "The party wall parapet, where present, needs its own detail — a lead cover flashing or a properly formed cap. If your neighbour is not replacing their fascia at the same time, we form a clean stop end at the boundary rather than trying to tie into their old cast iron. This is standard on terraced work and does not cost extra."),
      ("Do I need planning permission for fascia and soffit replacement?", "No, for like-for-like replacement on an unprotected structure. Yes, potentially, on a protected structure or in an ACA where the material or profile is changing. We flag this at survey stage rather than after quoting. --- Call (01) 265 8463 or use the contact form for a free survey. We go up and look rather than pricing from the ground — on a period Dublin terrace, the difference between a fascia repair and a full roofline replacement is not visible from the footpath."),
    ],
    links=[("/gutter-repairs", "Gutter repairs"), ("/new-gutters", "New gutters"), ("/fascia-soffit", "Fascia & soffit")]),
  dict(
    slug="downpipes-and-drainage-in-dublin",
    title="Downpipes and Drainage in Dublin",
    desc="Front-garden gullies, shared rear yards, and combined sewers — where the water actually ends up on a city terrace",
    cat="Costs", read=11, date="2026-09-22",
    lede="On most Dublin houses the downpipe discharges into a trapped gully at the base of the wall, which connects to either a combined sewer (Georgian and Victorian terraces, inner city) or a separate surface-water drain (post-1970s estates). Pooling and damp at the wall base almost always mean the gully is blocked, cracked, or the pipe is discharging beside it rather than into it.",
    body=[
      ("The short version",
       "<ul class=\"post-list\"><li><strong>Roughly 15–20 metres of gutter</strong> on a standard Dublin three-bed semi feeds two to four downpipes, each carrying the runoff from around 30–50 m² of roof.</li><li><strong>Pre-1970s inner-city terraces are on combined sewers</strong> — one pipe carries both foul waste and rainwater to the Ringsend treatment works, which is why Uisce Éireann restricts new surface-water connections into it.</li><li><strong>Newer estates from the 1970s onward</strong> are typically on separate systems, where the downpipe must go to the surface-water drain and never into the foul.</li><li><strong>A trapped gully with a 100mm water seal</strong> is what stops sewer smells rising back up the downpipe on a combined system — a dry or cracked gully is a common cause of drain odour at the front door.</li><li><strong>Damp at the base of the wall within 300mm of a downpipe</strong> points to the gully, the shoe, or the pipe joint above it — not to rising damp, and not to the gutter itself.</li><li><strong>Gutter repair on a Dublin semi runs €500–€800</strong> for a small job and <strong>€1,000–€1,900</strong> for a typical downpipe-and-alignment fix (indicative — confirmed free after a survey).</li></ul>"),
      ("Where the water goes when it leaves the roof",
       "<p>The gutter is the easy bit. The harder question — and the one that decides whether a wall stays dry — is what happens in the last two metres, between the shoe at the bottom of the downpipe and the ground.</p>\n        <p>On a Dublin house the water has one of three destinations:</p>\n        <ol class=\"post-list\"><li><strong>A trapped gully</strong> set into the path or the front garden, connected below ground to either a combined sewer or a surface-water drain.</li><li><strong>A back-inlet gully</strong> where the downpipe enters the drain below the grating, common on rear elevations and shared yards.</li><li><strong>A soakaway or channel drain</strong> on newer estates where the ground can take it, or where Uisce Éireann has required surface water to be dealt with on site.</li></ol>\n        <p>Which one you have is almost entirely a function of when the house was built and where in the city it sits. That is where the diagnosis starts.</p>"),
      ("1930s and 1940s semis — Cabra, Crumlin, Terenure, Clontarf",
       "<p>The classic pattern here is a two-pipe front elevation feeding trapped gullies in the front garden, with a single rear downpipe into a back-inlet gully in the yard. The original cast-iron pipes have almost all been replaced with 68mm uPVC round or 65mm square profile over the last thirty years.</p>\n        <p>Two things go wrong repeatedly on this stock:</p>\n        <p><strong>The gully cracks or silts up.</strong> The original clayware gullies are now ninety years old. Fine grit from the roof — moss, felt granules from a re-covered roof, wind-blown soil — builds up in the trap until water backs up and overflows onto the path. From there it tracks along the wall and shows up inside as damp on the skirting.</p>\n        <p><strong>The shoe misses the grating.</strong> A downpipe that has been re-clipped over the years often ends 100–150mm off-centre from the gully below. In light rain the water finds the drain anyway. In a Dublin downpour — the kind that dropped 40mm in an hour in the November 2023 event — half of it lands on the concrete beside the gully and soaks straight into the wall.</p>\n        <p>The fix is usually a new shoe, a new bearing on the lowest bracket, and a proper rod-and-jet of the gully. If the clayware trap has cracked, the gully itself gets swapped for a modern PVC one with a removable silt bucket. Our <a href=\"https://dublingutter.ie/\">gutter repairs</a> page covers the typical scope; the <a href=\"https://dublingutter.ie/\">downpipes</a> section deals specifically with the shoe-to-gully alignment.</p>"),
      ("Georgian and Victorian terraces — Rathmines, Portobello, Phibsborough, Drumcondra",
       "<p>These are the awkward ones, and the ones where a bad diagnosis costs the most.</p>\n        <p>The front elevation is straightforward — usually a single cast-iron downpipe at the party wall, discharging to a gully at the base of the steps or into a hopper at basement level. It is the <strong>rear</strong> that causes the arguments. A Victorian terrace typically has a shared rear yard, a shared return, and drainage that runs under someone else's flags before it reaches the main sewer at the front.</p>\n        <p>A few things worth knowing before spending money:</p>\n        <ul class=\"post-list\"><li><strong>The connection is almost always combined.</strong> Everything inside the old canal ring — foul, surface water, the lot — goes to one pipe and ends up at Ringsend. Uisce Éireann's stated position is that new surface-water connections into the combined network are not permitted where a separate outfall exists, but on Victorian stock a separate outfall usually does not exist, so the combined arrangement stays.</li><li><strong>The gully at the base of the rear downpipe is the smell trap for the whole yard.</strong> If it dries out in summer — no rain for a fortnight in Rathmines — the water seal fails and sewer gas rises up the downpipe. The fix is a bucket of water down the gully once a fortnight in dry weather, not a new drain.</li><li><strong>The party-wall downpipe is often shared.</strong> Cast-iron pipes on the boundary between two houses were sometimes installed as one pipe collecting both roofs via a hopper at eaves level. Repairs and replacements need agreement with the neighbour, and the <a href=\"https://dublingutter.ie/\">cast iron on period property</a> work carries a materials cost of around €50 per metre against €10 for uPVC.</li></ul>\n        <p>Where a Victorian rear yard is pooling in heavy rain, the cause is usually one of three things: the shared gully is silted, the below-ground pipe has a root intrusion at a clay joint, or the yard's own gully — separate from the downpipe — has failed. Only the first is a roofline job. The second is drainage. The third is paving.</p>"),
      ("1970s estates — Tallaght, Clondalkin, Coolock, Ballymun",
       "<p>Separate systems from here on. The rainwater downpipe <strong>must</strong> go to the surface-water drain, and the foul stack goes to the foul. Cross-connections — a rainwater pipe plumbed into the foul, or a washing machine draining into the surface-water gully — are a genuine problem in this age band and one Uisce Éireann has been active on since the misconnections work in the Dodder and Camac catchments.</p>\n        <p>The typical failure here is different again. The 112mm half-round gutter on a 1970s semi is often undersized for the roof it serves, so in a heavy shower the gutter overflows along the whole run rather than at the outlet. The downpipe never gets the water in the first place. Owners call for a downpipe clear; what they actually need is a <strong>125mm deep-flow upgrade</strong>, which is a full replacement on that elevation.</p>\n        <p>The <a href=\"https://dublingutter.ie/\">gutter cleaning</a> call sorts a blocked outlet. The overflow-along-the-run pattern is a sizing issue and a <a href=\"https://dublingutter.ie/\">full replacement</a> job.</p>"),
      ("Newer developments — Citywest, Adamstown, Clonsilla",
       "<p>Post-2000 estates are generally sound. Surface water is separated at the boundary, downpipes discharge to purpose-built gullies with silt buckets, and many sites have an on-plot soakaway or an attenuation tank that the downpipe feeds via a channel drain. The calls here are almost always blockages — a tennis ball in a hopper, a nesting bird in an offset — rather than design problems.</p>\n        <p>Two things to check on this stock before calling anyone:</p>\n        <ul class=\"post-list\"><li><strong>The gully grating lifts off.</strong> Have a look. Nine times out of ten there is a mat of oak or sycamore leaves sitting on top of the silt bucket. Lift it out, empty it, put it back. That is the whole job.</li><li><strong>The channel drain across the driveway is not the downpipe's drain.</strong> The downpipe has its own gully. If the channel drain is blocked, the driveway floods but the downpipe still runs.</li></ul>"),
      ("Diagnosing damp at the base of the wall",
       "<p>This is the call we get most often in October and November, once the first sustained wet week hits. The pattern to test for, in order:</p>\n        <ol class=\"post-list\"><li><strong>Is the damp within 300mm of a downpipe?</strong> If yes, the downpipe or its gully is the first suspect, not rising damp.</li><li><strong>Does it worsen in heavy rain within an hour?</strong> Rising damp is slow and constant. Downpipe-related damp tracks the weather.</li><li><strong>Is there staining on the render or the brick above the gully?</strong> A splash pattern 200–400mm up the wall means water is leaving the pipe and hitting the wall rather than entering the gully.</li><li><strong>Does the gully hold water when you pour a bucket in?</strong> A working trap holds the water. A cracked trap drains it away within seconds — that is the fault.</li><li><strong>Is there moss or a green stain running down the wall from a joint in the pipe?</strong> A split at a socket joint, common on brittle uPVC in south- and west-facing elevations after twenty years of UV.</li></ol>\n        <p>If four of the five point at the downpipe, it is a downpipe job. If none of them do, the damp is coming from somewhere else — a defective flashing, a cracked render, a leaking waste pipe — and a gutter contractor is the wrong first call.</p>"),
      ("What Uisce Éireann's rules mean for you in practice",
       "<p>The rules are simpler than they sound:</p>\n        <ul class=\"post-list\"><li>On a <strong>combined system</strong> (most pre-1970 inner Dublin), the existing downpipe-to-gully arrangement stays as it is. New work matches what is there.</li><li>On a <strong>separate system</strong> (most post-1970 estates), rainwater goes to the surface-water drain and only to the surface-water drain. A misconnection into the foul is a defect the seller has to disclose on a property sale.</li><li><strong>New impermeable area</strong> — a paved-over front garden, an extension — can trigger a requirement for on-site attenuation or a soakaway rather than a straight connection. This is a design question, not a gutter question, but it is worth knowing before the downpipe is moved.</li></ul>"),
      ("Indicative costs for downpipe and drainage work",
       "<p>All figures are indicative and confirmed free after a site survey.</p>\n        <div style=\"overflow-x:auto\"><table><thead><tr><th>Job</th><th>Typical cost</th></tr></thead><tbody><tr><td>Clear a blocked downpipe and gully, single stack</td><td>€500 – €800</td></tr><tr><td>Renew shoe, realign to gully, refix lowest bracket</td><td>€500 – €800</td></tr><tr><td>Replace one full uPVC downpipe (two-storey)</td><td>€1,000 – €1,900</td></tr><tr><td>Replace cast iron downpipe on period property</td><td>€1,900 – €3,000</td></tr><tr><td>Full elevation replacement including downpipes</td><td>See our <a href=\"https://dublingutter.ie/\">pricing page</a></td></tr></tbody></table></div>\n        <p>Below-ground drainage — root intrusion in the clay pipe under the path, a collapsed connection to the main sewer — is a drain contractor's job, not a guttering job. We will say so on the survey rather than quote for work that will not fix the fault.</p>"),
    ],
    faq=[
      ("How do I know if my downpipe is on the combined or the surface-water sewer?", "In practice: if the house was built before 1970 and sits inside the canal ring, assume combined. If it was built after 1970 in a suburban estate, assume separate. The council's drainage records for your street will confirm it; a request to Dublin City Council or the relevant local authority planning office will return the sewer map."),
      ("Why does my front-garden gully smell in summer?", "The water seal in the trap has dried out. Pour a bucket of water down the gully. If the smell returns within a week, the trap is cracked and the gully needs replacing — a half-hour job with a modern PVC gully and a silt bucket."),
      ("The downpipe discharges onto a concrete path with no gully. Is that a problem?", "Yes, on a Dublin house it almost always is. The splash wets the wall in every shower and the ground beside the wall never dries. A trapped gully cut into the path and connected to the nearest drain is the fix. On a rented property this is the landlord's responsibility."),
      ("Can I connect my new extension's downpipe into the existing gully?", "Usually yes, if the gully and the pipe below it can take the extra flow. On a combined system in an inner-city terrace, adding significant new roof area may require Uisce Éireann sign-off. Check before the roof goes on, not after."),
      ("Is a blocked downpipe covered by my home insurance if it causes damp?", "Damage from a sudden burst or storm event is usually covered, subject to the excess. Gradual damage from a long-blocked downpipe is treated as wear and tear and is not. Photograph any storm damage immediately and get a written report before repair."),
      ("Do you clear below-ground drains as well as downpipes?", "We clear the downpipe and the gully. Below-ground blockages — beyond the gully, into the connection to the main sewer — are a drain contractor's job. We will say so clearly on the survey. To arrange a free survey of your downpipes and drainage, call (01) 265 8463 or use the form on the site. We give a written breakdown before anything starts, and every job carries our 10-year written guarantee."),
    ],
    links=[("/gutter-cleaning", "Gutter cleaning"), ("/gutter-repairs", "Gutter repairs"), ("/fascia-soffit", "Fascia & soffit")]),
]
